Repository precice/precice, pull requests merged in 2019-11, with the labels that each got.

#548 delete copy and assign operator (C++11 feature)
  src/precice/SolverInterface.hpp
Labels: maintainability

#550 Fix XML Parser Messages not being handled
  src/xml/ConfigParser.cpp
  src/xml/ConfigParser.hpp
Labels: bug, usability

#536 Add configuration context to callback
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  src/action/config/ActionConfiguration.cpp
  src/action/config/ActionConfiguration.hpp
  src/action/tests/ScaleActionTest.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/tests/AbsoluteConvergenceMeasureTest.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/MinIterationConvergenceMeasureTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/io/config/ExportConfiguration.cpp
  src/io/config/ExportConfiguration.hpp
  src/io/tests/ExportConfigurationTest.cpp
  src/logging/config/LogConfiguration.cpp
  src/logging/config/LogConfiguration.hpp
  src/m2n/config/M2NConfiguration.cpp
  src/m2n/config/M2NConfiguration.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/mesh/config/DataConfiguration.cpp
  src/mesh/config/DataConfiguration.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/mesh/config/MeshConfiguration.hpp
  src/mesh/tests/DataConfigurationTest.cpp
  src/precice/config/Configuration.cpp
  src/precice/config/Configuration.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/config/SolverInterfaceConfiguration.cpp
  src/precice/config/SolverInterfaceConfiguration.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/ServerTests.cpp
  src/testing/Testing.hpp
  src/xml/ConfigParser.cpp
  src/xml/ConfigParser.hpp
  src/xml/XMLTag.cpp
  src/xml/XMLTag.hpp
  src/xml/tests/ParserTest.cpp
  src/xml/tests/XMLTest.cpp
  src/xml/tests/config_xmltest_context.xml
Labels: bug, enhancement, maintainability

#561 Fix missing check for optional occurrence
  src/xml/ConfigParser.cpp
Labels: bug

#583 Add debug log for ConnectionInfoReader
  src/com/ConnectionInfoPublisher.cpp
  src/com/ConnectionInfoPublisher.hpp
Labels: enhancement

#563 Add lazy evaluation to NP mapping
  src/mapping/NearestProjectionMapping.cpp
Labels: enhancement

#552 Add C++11 Library Conformance Check
  CMakeLists.txt
  cmake/CheckCXX11Library.cmake
Labels: building
