Repository precice/precice, pull requests merged in 2019-08, with the labels that each got.

#475 README.md: make Releases more prominent
  docs/README.md
Labels: usability

#477 Add getVersionInformation to API
  CMakeLists.txt
  SConstruct
  cmake/DetectGitRevision.cmake
  cmake/GenerateVersionInformation.cmake
  cmake/cmake_refresh_git_revision.cmake
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/tests/VersioningTests.cpp
  src/tests.cmake
  src/versions.cpp.in
  src/versions.hpp.in
Labels: enhancement

#382 Add option to pass custom MPI_Comm
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/userDefinedMPICommunicator.xml
  src/precice/tests/userDefinedMPICommunicatorPetRBF.xml
  src/testing/main.cpp
  src/utils/EventUtils.cpp
  src/utils/EventUtils.hpp
  src/utils/Petsc.cpp
Labels: enhancement

#471 Replace assertion with BOOST_TEST
  src/com/tests/CommunicateMeshTest.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/io/tests/ExportVTKXMLTest.cpp
  src/m2n/tests/GatherScatterCommunicationTest.cpp
  src/m2n/tests/PointToPointCommunicationTest.cpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/partition/tests/ProvidedPartitionTest.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/ServerTests.cpp
  src/query/tests/FindVoxelContentTest.cpp
  src/testing/tests/ExampleTests.cpp
  src/utils/tests/ParallelTest.cpp
Labels: bug

#485 Replaces ID management with a flat_set
  src/utils/ManageUniqueIDs.cpp
  src/utils/ManageUniqueIDs.hpp
Labels: enhancement

#490 Fix Throws
  src/action/config/ActionConfiguration.cpp
  src/com/config/CommunicationConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/PostProcessingConfiguration.cpp
  src/m2n/config/M2NConfiguration.cpp
  src/mesh/config/MeshConfiguration.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/xml/XMLTag.cpp
Labels: usability

#487 Scope Version Files
  CMakeLists.txt
  SConstruct
  cmake/DetectGitRevision.cmake
  src/logging/LogConfiguration.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/precice/SolverInterface.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/versions.cpp.in
  src/precice/impl/versions.hpp.in
  src/precice/tests/VersioningTests.cpp
  src/sources.cmake
  tools/updateSourceFiles.py
Labels: bug, maintainability
