Repository precice/precice, pull requests merged in 2019-02, with the labels that each got.

#241 Fix XML Validator Leaks
  CHANGELOG.md
  src/action/config/ActionConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/PostProcessingConfiguration.cpp
  src/logging/config/LogConfiguration.cpp
  src/m2n/config/M2NConfiguration.cpp
  src/mapping/config/MappingConfiguration.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/SolverInterfaceConfiguration.cpp
  src/xml/Validator.hpp
  src/xml/ValidatorEquals.hpp
  src/xml/ValidatorOr.cpph
  src/xml/ValidatorOr.hpp
  src/xml/XMLAttribute.hpp
  src/xml/XMLTag.hpp
  src/xml/tests/XMLTest.cpp
Labels: bug

#240 CMake Overhaul
  CHANGELOG.md
  CMakeLists.txt
  cmake/CPackConfig.cmake
  cmake/CopyTargetProperty.cmake
  cmake/PrintHelper.cmake
  cmake/modules/CorrectWindowsPaths.cmake
  cmake/modules/FindEigen3.cmake
  cmake/modules/FindNumPy.cmake
  cmake/modules/FindPETSc.cmake
  cmake/modules/FindPackageMultipass.cmake
  cmake/modules/ResolveCompilerPaths.cmake
  cmake/toolchain.hazelhen
  docs/man/man1/binprecice.1
  docs/man/man1/testprecice.1
  preciceConfig.cmake
  src/CMakeLists.txt
  src/sources.cmake
  src/tests.cmake
  tools/packaging/README.txt
  tools/packaging/WELCOME.txt
  tools/packaging/debian/copyright
  tools/solverdummies/cpp/CMakeLists.txt
  tools/updateSourceFiles.py
Labels: building, enhancement, usability

#258 WIP: Fix Flush Cache on Mapping clear
  src/mapping/NearestNeighborMapping.cpp
  src/mapping/NearestProjectionMapping.cpp
Labels: bug

#257 Add LibDL to CMake Configuration
  CMakeLists.txt
  cmake/modules/FindDL.cmake
Labels: bug, building

#216 General Doxygen Fixes
  Doxyfile
  src/action/Action.hpp
  src/cplscheme/impl/SVDFactorization.hpp
  src/precice/MeshHandle.hpp
  src/precice/SolverInterface.hpp
  src/precice/bindings/fortran/SolverInterfaceFASTEST.hpp
  src/precice/bindings/fortran/SolverInterfaceFortran.hpp
Labels: documentation

#185 Improve the clang-format support
  .clang-format
  tools/formatting/README.md
  tools/formatting/check-format
  tools/formatting/format-all
Labels: enhancement, usability

#268 Fix VTKXMLExporter not writing VertexNormals
  CHANGELOG.md
  src/io/ExportVTKXML.cpp
  src/io/tests/ExportVTKXMLTest.cpp
Labels: bug

#277 Restyle Doxygen
  Doxyfile
  docs/documents/000_main.dox
  docs/fragments/additional.css
  docs/fragments/logo.svg
Labels: documentation

#270 WIP Changing name of PySolverInterface to precice
  CHANGELOG.md
  src/precice/bindings/PySolverInterface/.gitignore
  src/precice/bindings/PySolverInterface/PySolverInterface/PySolverInterface.py
  src/precice/bindings/PySolverInterface/PySolverInterface/__init__.py
  src/precice/bindings/PySolverInterface/README.md
  src/precice/bindings/PySolverInterface/setup.py
  src/precice/bindings/python/.gitignore
  src/precice/bindings/python/PyConstants.pyx
  src/precice/bindings/python/README.md
  src/precice/bindings/python/build_and_install.sh
  src/precice/bindings/python/constants.pyx
  src/precice/bindings/python/precice.pyx
  src/precice/bindings/python/setup.py
  tools/solverdummies/python/solverdummy.py
Labels: enhancement

#288 Updating cpp solver dummy
  tools/solverdummies/cpp/.gitignore
  tools/solverdummies/cpp/README.md
  tools/solverdummies/cpp/main.cpp
  tools/solverdummies/cpp/precice-config.xml
  tools/solverdummies/python/solverdummy.py
Labels: bug, enhancement

#289 Fix petsc building with 64 bit indices
  tools/travis-install-dependencies.sh
Labels: bug

#299 Fix missing mpi4py
  tools/solverdummies/python/solverdummy.py
Labels: bug
