Repository precice/precice, pull requests merged in 2019-05, with the labels that each got.

#386 Add test_install
  CMakeLists.txt
  cmake/TestInstall.cmake
  tools/solverdummies/cpp/CMakeLists.txt
  tools/solverdummies/cpp/README.md
  tools/solverdummies/cpp/test.cmake
Labels: building, maintainability

#403 Fix constness of SolverInterface member functions
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
Labels: maintainability, usability

#389 Reproduce and fix #383
  src/cplscheme/impl/BaseQNPostProcessing.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/preconditioner-bug.xml
Labels: bug

#410 Rollback Nearest Projection Mapping
  src/mapping/NearestProjectionMapping.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/np-repartitioning.xml
Labels: bug

#417 Fix Eigen Includes
  src/action/ComputeCurvatureAction.cpp
  src/math/geometry.cpp
  src/mesh/Quad.cpp
  src/mesh/Triangle.cpp
Labels: bug
