Repository precice/precice, pull requests merged in 2019-12, with the labels that each got.

#554 Fix assertion in getMeshVertexIDsFromPositions
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: bug

#584 Change the Debug output for first mapped values.
  src/precice/impl/SolverInterfaceImpl.cpp
  src/utils/EigenHelperFunctions.hpp
  src/utils/algorithm.hpp
  src/utils/tests/AlgorithmTest.cpp
  src/utils/tests/EigenHelperFunctionsTest.cpp
Labels: usability

#595 Reduce parallel tests
  src/action/tests/PythonActionTest.cpp
  src/action/tests/ScaleActionTest.cpp
  src/cplscheme/tests/AbsoluteConvergenceMeasureTest.cpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/mapping/tests/NearestNeighborMappingTest.cpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/math/tests/BarycenterTest.cpp
  src/math/tests/DifferencesTest.cpp
  src/math/tests/GeometryTest.cpp
  src/mesh/tests/DataConfigurationTest.cpp
  src/mesh/tests/EdgeTest.cpp
  src/mesh/tests/GroupTest.cpp
  src/mesh/tests/MergeTest.cpp
  src/mesh/tests/MeshTest.cpp
  src/mesh/tests/PropertyContainerTest.cpp
  src/mesh/tests/QuadTest.cpp
  src/mesh/tests/RTreeTests.cpp
  src/mesh/tests/TriangleTest.cpp
  src/mesh/tests/VertexTest.cpp
  src/query/tests/FindClosestTest.cpp
  src/query/tests/FindClosestVertexVisitorTest.cpp
  src/testing/main.cpp
  src/utils/tests/AlgorithmTest.cpp
  src/utils/tests/DimensionsTest.cpp
  src/utils/tests/EigenHelperFunctionsTest.cpp
  src/utils/tests/ManageUniqueIDsTest.cpp
  src/utils/tests/MultiLockTest.cpp
  src/utils/tests/PointerVectorTest.cpp
  src/utils/tests/StatisticsTest.cpp
  src/utils/tests/StringTest.cpp
  src/xml/tests/ParserTest.cpp
  src/xml/tests/XMLTest.cpp
Labels: maintainability

#571 Add Markdown Reference Generator
  CHANGELOG.md
  src/drivers/main.cpp
  src/sources.cmake
  src/tests.cmake
  src/xml/Printer.cpp
  src/xml/Printer.hpp
  src/xml/XMLAttribute.hpp
  src/xml/XMLTag.cpp
  src/xml/XMLTag.hpp
  src/xml/tests/PrinterTest.cpp
Labels: enhancement

#580 PR draft MATLAB bindings
  src/precice/bindings/matlab/+precice/@SolverInterface/SolverInterface.m
  src/precice/bindings/matlab/+precice/@SolverInterface/private/preciceGateway.cpp
  src/precice/bindings/matlab/+precice/@SolverInterfaceOOP/SolverInterfaceOOP.m
  src/precice/bindings/matlab/README.md
  src/precice/bindings/matlab/tutorial/README.md
  src/precice/bindings/matlab/tutorial/explicit/Solver_I.m
  src/precice/bindings/matlab/tutorial/explicit/Solver_U.m
  src/precice/bindings/matlab/tutorial/explicit/precice-config.xml
  src/precice/bindings/matlab/tutorial/implicit/Solver_I.m
  src/precice/bindings/matlab/tutorial/implicit/Solver_U.m
  src/precice/bindings/matlab/tutorial/implicit/precice-config.xml
  src/precice/bindings/matlab/tutorial/ref_images/Sample_Curves.png
  src/precice/bindings/matlab/tutorial/ref_images/diagram.svg
  tools/solverdummies/matlab/solverdummy.m
Labels: enhancement

#572 Simplify parallel configuration
  CHANGELOG.md
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/explicit-coupling-scheme-1.xml
  src/cplscheme/tests/explicit-coupling-scheme-2.xml
  src/cplscheme/tests/multi-solver-coupling-1.xml
  src/cplscheme/tests/multi-solver-coupling-2.xml
  src/cplscheme/tests/multi-solver-coupling-3.xml
  src/cplscheme/tests/multi-solver-coupling-4.xml
  src/cplscheme/tests/parallel-explicit-coupling-datainit.xml
  src/cplscheme/tests/serial-explicit-coupling-datainit.xml
  src/m2n/GatherScatterCommunication.cpp
  src/m2n/M2N.cpp
  src/m2n/M2N.hpp
  src/m2n/PointToPointCommunication.cpp
  src/m2n/config/M2NConfiguration.cpp
  src/m2n/config/M2NConfiguration.hpp
  src/m2n/tests/GatherScatterCommunicationTest.cpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/partition/ProvidedPartition.cpp
  src/partition/ReceivedPartition.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/tests/QN1.xml
  src/precice/tests/QN2.xml
  src/precice/tests/QN3.xml
  src/precice/tests/ServerTests.cpp
  src/precice/tests/bug.xml
  src/precice/tests/explicit-mpi.xml
  src/precice/tests/explicit-sockets.xml
  src/precice/tests/gather-scatter-mpi.xml
  src/precice/tests/globalRBFPartitioning.xml
  src/precice/tests/line-coupling.xml
  src/precice/tests/localRBFPartitioning.xml
  src/precice/tests/mapping-without-geo-2D.xml
  src/precice/tests/mapping-without-geo-3D.xml
  src/precice/tests/master-sockets.xml
  src/precice/tests/np-repartitioning.xml
  src/precice/tests/point-to-point-mpi.xml
  src/precice/tests/point-to-point-sockets.xml
  src/precice/tests/userDefinedMPICommunicator.xml
  src/precice/tests/userDefinedMPICommunicatorPetRBF.xml
  src/testing/Fixtures.hpp
  src/testing/main.cpp
  src/utils/EventUtils.cpp
  src/utils/MasterSlave.cpp
Labels: breaking change, usability

#566 Refactor meshids
  src/acceleration/test/AccelerationMasterSlaveTest.cpp
  src/action/tests/PythonActionTest.cpp
  src/action/tests/ScaleActionTest.cpp
  src/com/tests/CommunicateMeshTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/io/tests/ExportVTKTest.cpp
  src/io/tests/ExportVTKXMLTest.cpp
  src/m2n/tests/GatherScatterCommunicationTest.cpp
  src/m2n/tests/PointToPointCommunicationTest.cpp
  src/mapping/tests/NearestNeighborMappingTest.cpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/mesh/config/MeshConfiguration.hpp
  src/mesh/tests/MeshTest.cpp
  src/mesh/tests/RTreeTests.cpp
  src/partition/ProvidedPartition.cpp
  src/partition/ReceivedBoundingBox.cpp
  src/partition/ReceivedPartition.cpp
  src/partition/tests/ProvidedBoundingBoxTest.cpp
  src/partition/tests/ProvidedPartitionTest.cpp
  src/partition/tests/ReceivedBoundingBoxTest.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/Participant.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/tests/MeshHandleTest.cpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/ServerTests.cpp
  src/precice/tests/WatchPointTest.cpp
  src/query/tests/FindClosestTest.cpp
  src/query/tests/FindClosestVertexVisitorTest.cpp
  src/testing/Testing.hpp
Labels: maintainability
