Repository precice/precice, pull requests merged in 2019-07, with the labels that each got.

#447 Add CTest MPI Flags
  CMakeLists.txt
  cmake/CTestConfig.cmake
Labels: usability

#449 Modernize Non-Copyable Base Classes
  src/action/Action.hpp
  src/com/Communication.hpp
  src/cplscheme/CouplingScheme.hpp
  src/io/Export.hpp
  src/io/Import.hpp
  src/mapping/Mapping.hpp
  src/mesh/Edge.hpp
  src/mesh/Mesh.hpp
  src/mesh/PropertyContainer.hpp
  src/mesh/Quad.hpp
  src/mesh/Triangle.hpp
  src/mesh/Vertex.hpp
  src/partition/Partition.hpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/xml/XMLTag.hpp
Labels: maintainability

#448 Fix bug for non contiguous numpy arrays
  src/precice/bindings/python/precice/precice.py
  src/precice/bindings/python/test/solverdummy.py
  src/precice/bindings/python_future/.gitignore
  src/precice/bindings/python_future/SolverInterface.pxd
  src/precice/bindings/python_future/precice_future.pyx
  src/precice/bindings/python_future/test/SolverInterface.cpp
  src/precice/bindings/python_future/test/test_bindings_module.pyx
Labels: bug

#455 Add additional info in the connection stage
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability

#461 Add check for empty participant name
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability

#466 Add events for mapping internals
  src/mapping/NearestNeighborMapping.cpp
  src/mapping/NearestProjectionMapping.cpp
  src/partition/ReceivedPartition.cpp
Labels: usability
