Repository precice/precice, pull requests merged in 2019-01, with the labels that each got.

#214 Improve Doxygen Namespace Documentation
  Doxyfile
  docs/documents/namespaces.dox
  src/math/barycenter.hpp
  src/utils/Petsc.hpp
Labels: documentation

#234 Remove Footer in Doxygen
  Doxyfile
  docs/fragments/footer.html
Labels: documentation

#204 Migrate stacktrace to boost::stacktrace
  CHANGELOG.md
  SConstruct
  src/io/ExportVTK.cpp
  src/m2n/PointToPointCommunication.cpp
  src/utils/stacktrace.cpp
  src/utils/stacktrace.hpp
Labels: enhancement, usability

#219 Fixing relative path
  src/precice/bindings/python/setup.py
Labels: bug

#232 Tooling Page for Doxygen
  docs/documents/020_conventions.dox
  docs/documents/070_tooling.dox
Labels: documentation

#242 Fix Leaks in Mesh
  src/mesh/Mesh.cpp
Labels: bug
