Repository precice/precice, pull requests merged in 2020-04, with the labels that each got.

#710 Bugfix v2.0.2
  CHANGELOG.md
  CMakeLists.txt
  src/partition/ReceivedPartition.cpp
  src/testing/main.cpp
  tools/releasing/packaging/debian/changelog
Labels: bug

#707 Summation action
  .gitignore
  src/action/SummationAction.cpp
  src/action/SummationAction.hpp
  src/action/config/ActionConfiguration.cpp
  src/action/config/ActionConfiguration.hpp
  src/action/tests/SummationActionTest-testConfiguration-1.xml
  src/action/tests/SummationActionTest.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/summation-action.xml
  src/sources.cmake
  src/tests.cmake
Labels: enhancement

#708 Simplify FindNumPy
  CHANGELOG.md
  cmake/modules/FindNumPy.cmake
Labels: maintainability

#703 Remove Manifold Mapping
  CHANGELOG.md
  src/acceleration/Acceleration.hpp
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/AitkenAcceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/ConstantRelaxationAcceleration.cpp
  src/acceleration/ConstantRelaxationAcceleration.hpp
  src/acceleration/MMAcceleration.cpp
  src/acceleration/MMAcceleration.hpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/impl/AbsoluteConvergenceMeasure.hpp
  src/cplscheme/impl/ConvergenceMeasure.hpp
  src/cplscheme/impl/MinIterationConvergenceMeasure.hpp
  src/cplscheme/impl/RelativeConvergenceMeasure.hpp
  src/cplscheme/impl/ResidualRelativeConvergenceMeasure.hpp
  src/cplscheme/tests/AbsoluteConvergenceMeasureTest.cpp
  src/cplscheme/tests/MinIterationConvergenceMeasureTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/RelativeConvergenceMeasureTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/sources.cmake
Labels: maintainability

#723 Extend ReceivedPartition PetRBF tests to also handle PETSc < v3.8
  src/partition/tests/ReceivedPartitionTest.cpp
Labels: petsc

#742 Write events summary to file
  docs/changelog/742.md
  src/utils/EventUtils.cpp
Labels: usability

#745 Fix BoundingBox failure of systemtests on Ubuntu16.04
  src/com/tests/CommunicateBoundingBoxTest.cpp
  src/partition/tests/ProvidedPartitionTest.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
Labels: bug, building
