Repository precice/precice, pull requests merged in 2020-01, with the labels that each got.

#481 Make Pythonactions compatible with Python 2 and 3
  .travis.yml
  CHANGELOG.md
  CMakeLists.txt
  cmake/modules/FindNumPy.cmake
  src/action/PythonAction.cpp
Labels: building, maintainability, usability

#608 Remove MeshHandle
  CHANGELOG.md
  src/precice/MeshHandle.cpp
  src/precice/MeshHandle.hpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/MeshHandleTest.cpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/sources.cmake
  src/tests.cmake
Labels: breaking change, maintainability

#614 Single-step setup
  CHANGELOG.md
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/bindings/c/SolverInterfaceC.cpp
  src/precice/bindings/fortran/SolverInterfaceFASTEST.cpp
  src/precice/bindings/fortran/SolverInterfaceFortran.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/testing/Testing.hpp
  tools/solverdummies/cpp/solverdummy.cpp
Labels: breaking change, maintainability, usability

#609 Clarify CMake Variables
  CHANGELOG.md
  CMakeLists.txt
  cmake/BackwardsCompatibility.cmake
  cmake/CTestConfig.cmake
  cmake/PrintHelper.cmake
  cmake/XSDKOptions.cmake
  tools/travis-build-test.sh
  tools/travis-coverage.sh
Labels: breaking change, maintainability

#631 Rename fulfilledAction -> markActionFulfilled, closes #546
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/bindings/c/SolverInterfaceC.cpp
  src/precice/bindings/c/SolverInterfaceC.h
  src/precice/bindings/fortran/SolverInterfaceFASTEST.cpp
  src/precice/bindings/fortran/SolverInterfaceFASTEST.hpp
  src/precice/bindings/fortran/SolverInterfaceFortran.cpp
  src/precice/bindings/fortran/SolverInterfaceFortran.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
Labels: breaking change, usability

#638 Documentation: Add clarifications for clang-format
  docs/documents/070_tooling.dox
  tools/formatting/README.md
Labels: documentation

#634 C-bindings: Use precice::SolverInterface instead of precice::impl::SolverInterfaceImpl
  extras/bindings/c/src/SolverInterfaceC.cpp
Labels: maintainability

#635 Add getVersionInformation to C, Fortran bindings
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
Labels: enhancement

#646 Remove last traces of SCons
  docs/documents/060_release.dox
  examples/solverdummies/README.md
  examples/solverdummies/c/README.md
  examples/solverdummies/c/SConstruct
  examples/solverdummies/cpp/README.md
Labels: building

#650 Add safety check for user defined MPI Communicator
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability
