Repository precice/precice, pull requests merged in 2020-11, with the labels that each got.

#876 Refactor extrapolateData
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
Labels: maintainability

#890 Fix and extend the FindPETSc module
  cmake/modules/FindPETSc.cmake
Labels: bug

#886 Complete XML documentation
  docs/changelog/886.md
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  src/action/config/ActionConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/logging/config/LogConfiguration.cpp
  src/mapping/config/MappingConfiguration.cpp
  src/mesh/config/DataConfiguration.cpp
Labels: documentation

#892 Fix boost log_level for macOS
  src/testing/main.cpp
Labels: bug

#894 Fix out-of-range bug in local RBF ReceivedPartitionTest
  src/partition/tests/ReceivedPartitionTest.cpp
Labels: bug

#895 Fix missing overrides
  src/m2n/GatherScatterCommunication.hpp
  src/m2n/PointToPointCommunication.hpp
Labels: building

#881 Implement watch integral
  docs/changelog/881.md
  src/mesh/Edge.cpp
  src/mesh/Edge.hpp
  src/mesh/Triangle.cpp
  src/mesh/Triangle.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/impl/Participant.cpp
  src/precice/impl/Participant.hpp
  src/precice/impl/SharedPointer.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/WatchIntegral.cpp
  src/precice/impl/WatchIntegral.hpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/WatchIntegralTest.cpp
  src/precice/tests/watch-integral.xml
  src/sources.cmake
  src/tests.cmake
Labels: enhancement

#902 Enforce max-iterations tag for implicit cpl schemes
  docs/changelog/902.md
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
Labels: bug

#905 Fix QR factorization assertions
  docs/changelog/905.md
  src/acceleration/impl/QRFactorization.cpp
  src/precice/tests/ParallelTests.cpp
Labels: bug

#900 Fix vector access patterns
  examples/solverdummies/cpp/solverdummy.cpp
  src/acceleration/test/ParallelMatrixOperationsTest.cpp
  src/action/tests/ScaleActionTest.cpp
  src/action/tests/SummationActionTest.cpp
  src/com/tests/CommunicateBoundingBoxTest.cpp
  src/com/tests/CommunicateMeshTest.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/io/tests/ExportVTKTest.cpp
  src/io/tests/ExportVTKXMLTest.cpp
  src/m2n/tests/GatherScatterCommunicationTest.cpp
  src/m2n/tests/PointToPointCommunicationTest.cpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/math/tests/GeometryTest.cpp
  src/mesh/tests/DataConfigurationTest.cpp
  src/mesh/tests/MeshTest.cpp
  src/mesh/tests/RTreeTests.cpp
  src/partition/tests/ProvidedPartitionTest.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
  src/precice/tests/SerialTests.cpp
  src/query/tests/FindClosestTest.cpp
  src/utils/tests/AlgorithmTest.cpp
  src/utils/tests/ParallelTest.cpp
Labels: maintainability
