Repository precice/precice, pull requests merged in 2020-09, with the labels that each got.

#855 Add BUILD_TESTING option (default ON) to in/exclude building of tests
  CMakeLists.txt
Labels: building

#863 Fix error message for unique acceleration subtags
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
Labels: bug

#862 Add support for escaped XML characters
  docs/changelog/862.md
  src/xml/ConfigParser.cpp
  src/xml/ConfigParser.hpp
  src/xml/tests/ParserTest.cpp
Labels: bug

#868 Make locale selection optional
  docs/changelog/868.md
  src/xml/ValueParser.cpp
Labels: bug

#843 Add GitHub Actions CI
  .github/workflows/build-and-test.yml
Labels: maintainability

#836 Update PKGBUILD (add PETSc and NumPy, run tests, update for v2.1.0)
  tools/releasing/packaging/Arch_User_Repository/PKGBUILD
Labels: building
