Repository precice/precice, pull requests merged in 2020-07, with the labels that each got.

#780 Add oversubscribe flag to test environment
  cmake/CTestConfig.cmake
  docs/changelog/780.md
Labels: usability

#730 Improve further API errors, Section 2.5
  src/cplscheme/BaseCouplingScheme.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability

#725 Improve numerical error messages (Section 4)
  src/acceleration/BaseQNAcceleration.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
Labels: usability

#784 Re-enable p2p in parallel integration tests, see #599
  src/precice/tests/QN1.xml
  src/precice/tests/QN2.xml
  src/precice/tests/QN3.xml
  src/precice/tests/line-coupling.xml
Labels: bug

#787 Introduce several checks to prevent wrong preCICE usage in QN acc
  docs/changelog/787.md
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/impl/ResidualSumPreconditioner.cpp
  src/precice/tests/SerialTests.cpp
Labels: bug

#792 Bump required PETSc version to 3.12
  CMakeLists.txt
  docs/changelog/792.md
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
Labels: petsc

#793 Relax quasi-Newton check to warning
  src/acceleration/BaseQNAcceleration.cpp
Labels: bug

#795 Move reduceVector to Eigen helper functions
  src/mapping/RadialBasisFctMapping.hpp
  src/utils/EigenHelperFunctions.cpp
  src/utils/EigenHelperFunctions.hpp
Labels: bug, building

#797 Add warings when configuring OpenMPI with MPI m2n
  docs/changelog/797.md
  src/m2n/config/M2NConfiguration.cpp
Labels: usability

#744 Improve errors messages of section 1.6
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/impl/AbsoluteConvergenceMeasure.cpp
  src/cplscheme/impl/RelativeConvergenceMeasure.cpp
  src/cplscheme/impl/ResidualRelativeConvergenceMeasure.cpp
Labels: enhancement

#803 Extend the information of various configuration error messages (Section 1.8)
  src/m2n/config/M2NConfiguration.cpp
  src/partition/ProvidedPartition.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability

#799 Convergence measure logging overhaul
  docs/changelog/799.md
  src/acceleration/Acceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/impl/QRFactorization.cpp
  src/acceleration/impl/QRFactorization.hpp
  src/acceleration/test/AccelerationMasterSlaveTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/impl/AbsoluteConvergenceMeasure.hpp
  src/cplscheme/impl/ConvergenceMeasure.hpp
  src/cplscheme/impl/RelativeConvergenceMeasure.hpp
  src/cplscheme/impl/ResidualRelativeConvergenceMeasure.hpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ResidualRelativeConvergenceMeasureTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/io/TXTTableWriter.cpp
  src/tests.cmake
Labels: usability

#804 Improve error messages concerning the interface constructor (Section 2.1)
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability

#811 Bugfix and test for implicit coupling and initialize data
  src/cplscheme/BaseCouplingScheme.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/implicit-data-init.xml
Labels: bug

#806 Errors 2.2 - Steering
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
Labels: usability

#728 Improve errors: Data and mesh config
  src/mesh/Mesh.cpp
  src/mesh/config/DataConfiguration.cpp
  src/mesh/config/MeshConfiguration.cpp
Labels: usability

#817 Errors 2.3 - Mesh Definition
  src/mesh/Mesh.cpp
  src/partition/ProvidedPartition.cpp
  src/partition/ReceivedPartition.cpp
  src/precice/impl/CommonErrorMessages.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: maintainability, usability

#805 Fix parsing locale
  docs/changelog/805.md
  src/xml/ValueParser.cpp
  src/xml/ValueParser.hpp
  src/xml/XMLAttribute.hpp
Labels: bug

#818 Add strict convergence option
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/convergence-measures1.xml
  src/precice/tests/convergence-measures2.xml
  src/precice/tests/convergence-measures3.xml
Labels: usability

#808 Errors 1.9 - Technical Config
  src/mesh/config/DataConfiguration.cpp
  src/precice/config/SolverInterfaceConfiguration.cpp
  src/xml/ConfigParser.cpp
  src/xml/XMLAttribute.hpp
  src/xml/XMLTag.cpp
Labels: usability

#659 Update PR template
  .github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
Labels: documentation

#832 Update information of PETSc in CMake
  CMakeLists.txt
Labels: usability

#830 Rename LU decomposition to QR in configuration
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/precice/tests/bug.xml
  src/precice/tests/mapping-without-geo-2D.xml
  src/precice/tests/mapping-without-geo-3D.xml
Labels: usability
