Repository precice/precice, pull requests merged in 2020-06, with the labels that each got.

#709 Add connectMasterSlaves to Communication
  src/com/Communication.cpp
  src/com/Communication.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/testing/TestContext.cpp
Labels: maintainability

#775 Simplify and Refactor Basis Functions
  src/mapping/impl/BasisFunctions.hpp
Labels: maintainability

#776 Migrate Fortran bindings to use unique_ptr
  docs/changelog/776.md
  extras/bindings/fortran/src/SolverInterfaceFASTEST.cpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
Labels: enhancement

#772 Fix Resource Finalization of SolverInterface
  docs/changelog/772.md
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/lifecycle.xml
Labels: bug

#763 Forbid Watchpoint on Receiving Meshes
  docs/changelog/763.md
  src/precice/config/ParticipantConfiguration.cpp
Labels: usability

#760 Re-enable reset of written data at the end of advance
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/tests/BB-sockets-explicit-twoway.xml
  src/precice/tests/ParallelTests.cpp
Labels: usability

#486 Add Watchpoint Reinitialisation
  src/io/TXTTableWriter.cpp
  src/io/TXTTableWriter.hpp
  src/io/tests/TXTTableWriterTest.cpp
  src/precice/impl/WatchPoint.cpp
  src/precice/impl/WatchPoint.hpp
  src/precice/tests/WatchPointTest.cpp
Labels: maintainability

#739 Gather-scatter LU decomposition for parallel RBF mappings
  docs/changelog/739.md
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/globalRBFPartitioning.xml
  src/precice/tests/localRBFPartitioning.xml
Labels: usability
