Repository precice/precice, pull requests merged in 2020-10, with the labels that each got.

#871 Update removes build/last and adds mpirun -np 4
  docs/documents/050_tests.dox
Labels: documentation

#759 Add CI Format Checker
  .github/workflows/code-style.yml
Labels: maintainability

#865 Refactor CouplingData
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BroydenAcceleration.cpp
  src/acceleration/ConstantRelaxationAcceleration.cpp
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/MVQNAcceleration.cpp
  src/acceleration/test/AccelerationMasterSlaveTest.cpp
  src/action/ComputeCurvatureAction.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/CouplingData.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
Labels: enhancement

#874 Fix compilation error on intel
  docs/changelog/874.md
  src/partition/tests/ProvidedPartitionTest.cpp
Labels: bug
