Repository precice/precice, pull requests merged in 2021-09, with the labels that each got.

#1038 Refactor DataContext
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/Participant.cpp
  src/precice/impl/Participant.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/tests/DataContextTest.cpp
  src/tests.cmake
Labels: maintainability

#1068 Prevent name resolution in sockets
  docs/changelog/1068.md
  src/com/SocketCommunication.cpp
Labels: bug

#1077 Build shared libraries by default
  .github/workflows/build-and-test-mac.yml
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  docs/changelog/1077.md
  tools/building/compileAndTest.py
Labels: building

#1084 Clean-up direct access functionality
  src/precice/SolverInterface.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/explicit-direct-access-read.xml
Labels: bug

#624 Change default mpi com in m2n to MPISinglePortsCom
  docs/changelog/624.md
  src/m2n/config/M2NConfiguration.cpp
  src/precice/tests/explicit-mpi-single-non-inc.xml
  src/precice/tests/explicit-mpi-single.xml
  src/precice/tests/explicit-mpi.xml
Labels: usability

#1080 Add Access to Mesh Requirements via API
  docs/changelog/1080.md
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/meshrequirements-nn.xml
  src/precice/tests/meshrequirements-np.xml
Labels: enhancement

#1093 Print logs and infos consistently with fixed width
  docs/changelog/1093.md
  src/cplscheme/impl/AbsoluteConvergenceMeasure.hpp
  src/cplscheme/impl/RelativeConvergenceMeasure.hpp
  src/cplscheme/impl/ResidualRelativeConvergenceMeasure.hpp
  src/io/TXTTableWriter.cpp
Labels: usability

#1092 Updates difference matrices if residuals are not zero only
  docs/changelog/1092.md
  src/acceleration/BaseQNAcceleration.cpp
Labels: bug

#1097 Fix used order depending on window
  docs/changelog/1097.md
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/time/Waveform.cpp
  src/time/tests/WaveformTest.cpp
Labels: bug
