Repository precice/precice, pull requests merged in 2021-04, with the labels that each got.

#993 Use PKG_CONFIG_ALLOW_SYSTEM_CFLAGS in FindPETSc
  cmake/modules/FindPETSc.cmake
  docs/changelog/993.md
Labels: bug

#1002 Modernize deprecated headers
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/BroydenAcceleration.cpp
  src/acceleration/impl/QRFactorization.cpp
  src/acceleration/impl/ResidualPreconditioner.cpp
  src/acceleration/impl/ResidualSumPreconditioner.cpp
  src/acceleration/impl/ValuePreconditioner.cpp
  src/com/CommunicateBoundingBox.cpp
  src/com/CommunicateMesh.cpp
  src/com/MPICommunication.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/mapping/config/MappingConfiguration.cpp
  src/math/geometry.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/utils/MasterSlave.cpp
  src/xml/Printer.cpp
Labels: maintainability

#997 Replace prettyprint with fmtlib
  CMakeLists.txt
  cmake/Validation.cmake
  docs/changelog/997.md
  src/acceleration/BaseQNAcceleration.cpp
  src/action/PythonAction.cpp
  src/com/MPIDirectCommunication.cpp
  src/com/MPIPortsCommunication.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/logging/LogMacros.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/math/tests/BarycenterTest.cpp
  src/math/tests/GeometryTest.cpp
  src/mesh/BoundingBox.cpp
  src/mesh/Mesh.cpp
  src/mesh/config/DataConfiguration.cpp
  src/mesh/config/MeshConfiguration.cpp
  src/mesh/tests/MeshTest.cpp
  src/precice/config/SolverInterfaceConfiguration.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/sources.cmake
  src/tests.cmake
  src/utils/ArgumentFormatter.hpp
  src/utils/Parallel.cpp
  src/utils/assertion.hpp
  src/utils/fmt.hpp
  src/utils/fmtEigen.hpp
  src/utils/fmtSTL.hpp
  thirdparty/prettyprint/CMakeLists.txt
  thirdparty/prettyprint/include/prettyprint/prettyprint.hpp
Labels: maintainability

#935 Clarify time step vs. time window vs. dt
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/BroydenAcceleration.cpp
  src/acceleration/BroydenAcceleration.hpp
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/IQNILSAcceleration.hpp
  src/acceleration/MVQNAcceleration.cpp
  src/acceleration/MVQNAcceleration.hpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  src/acceleration/impl/ConstantPreconditioner.cpp
  src/acceleration/impl/ConstantPreconditioner.hpp
  src/acceleration/impl/Preconditioner.hpp
  src/acceleration/impl/ResidualPreconditioner.cpp
  src/acceleration/impl/ResidualPreconditioner.hpp
  src/acceleration/impl/ResidualSumPreconditioner.cpp
  src/acceleration/impl/ResidualSumPreconditioner.hpp
  src/acceleration/impl/ValuePreconditioner.cpp
  src/acceleration/impl/ValuePreconditioner.hpp
  src/acceleration/test/AccelerationMasterSlaveTest.cpp
  src/acceleration/test/PreconditionerTest.cpp
  src/action/Action.hpp
  src/action/ComputeCurvatureAction.cpp
  src/action/ComputeCurvatureAction.hpp
  src/action/PythonAction.cpp
  src/action/PythonAction.hpp
  src/action/PythonAction.py
  src/action/RecorderAction.cpp
  src/action/RecorderAction.hpp
  src/action/ScaleByAreaAction.cpp
  src/action/ScaleByAreaAction.hpp
  src/action/ScaleByDtAction.cpp
  src/action/ScaleByDtAction.hpp
  src/action/SummationAction.cpp
  src/action/SummationAction.hpp
  src/action/config/ActionConfiguration.cpp
  src/action/config/ActionConfiguration.hpp
  src/action/tests/ScaleActionTest.cpp
  src/action/tests/TestAllAction.py
  src/action/tests/TestOmitAction1.py
  src/action/tests/TestOmitAction2.py
  src/action/tests/TestOmitAction3.py
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
Labels: bug, documentation, maintainability
