Repository precice/precice, pull requests merged in 2021-06, with the labels that each got.

#1004 Package time
  cmake/CTestConfig.cmake
  docs/changelog/1004.md
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BroydenAcceleration.cpp
  src/acceleration/ConstantRelaxationAcceleration.cpp
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/MVQNAcceleration.cpp
  src/acceleration/test/AccelerationMasterSlaveTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/SharedPointer.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/sources.cmake
  src/tests.cmake
  src/time/SharedPointer.hpp
  src/time/Waveform.cpp
  src/time/Waveform.hpp
  src/time/tests/WaveformTest.cpp
  src/utils/EigenHelperFunctions.cpp
  src/utils/EigenHelperFunctions.hpp
Labels: enhancement

#1025 Multi-coupling extension
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/m2n/config/M2NConfiguration.cpp
  src/m2n/config/M2NConfiguration.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/multi-coupling-four-solver-1.xml
  src/precice/tests/multi-coupling-four-solver-2.xml
  src/precice/tests/multi-coupling-three-solver-1.xml
  src/precice/tests/multi-coupling-three-solver-2.xml
  src/precice/tests/multi-coupling-three-solver-3.xml
Labels: enhancement

#1037 Refactor mapReadData and mapWrittenData
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
Labels: maintainability

#1031 Print Eigen3_ROOT info when Eigen3 detection fails
  cmake/modules/FindEigen3.cmake
Labels: building
