Repository precice/precice, pull requests merged in 2021-08, with the labels that each got.

#1049 Refactor Mesh Index
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/precice/impl/WatchPoint.cpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/tests/RTreeTests.cpp
Labels: maintainability

#1051 Code simplifications w.r.t mesh->data().at(ID)
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/tests/MeshTest.cpp
Labels: maintainability

#1053 Port communication backend to using span
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/impl/ParallelMatrixOperations.hpp
  src/acceleration/test/ParallelMatrixOperationsTest.cpp
  src/com/Communication.cpp
  src/com/Communication.hpp
  src/com/MPICommunication.cpp
  src/com/MPICommunication.hpp
  src/com/MPIDirectCommunication.cpp
  src/com/MPIDirectCommunication.hpp
  src/com/SocketCommunication.cpp
  src/com/SocketCommunication.hpp
  src/com/tests/GenericTestFunctions.hpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/m2n/DistributedCommunication.hpp
  src/m2n/GatherScatterCommunication.cpp
  src/m2n/GatherScatterCommunication.hpp
  src/m2n/M2N.cpp
  src/m2n/M2N.hpp
  src/m2n/PointToPointCommunication.cpp
  src/m2n/PointToPointCommunication.hpp
  src/m2n/tests/GatherScatterCommunicationTest.cpp
  src/m2n/tests/PointToPointCommunicationTest.cpp
  src/mapping/RadialBasisFctMapping.hpp
  src/precice/impl/WatchIntegral.cpp
  src/utils/MasterSlave.cpp
  src/utils/MasterSlave.hpp
  src/utils/span.hpp
  src/utils/span_tools.hpp
Labels: maintainability

#1056 Use getters of Mesh and Data
  src/acceleration/config/AccelerationConfiguration.cpp
  src/action/config/ActionConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/mesh/config/MeshConfiguration.hpp
  src/precice/config/ParticipantConfiguration.cpp
Labels: enhancement

#1070 Test data read and write for subcycling
  src/precice/tests/SerialTests.cpp
  src/precice/tests/explicit-scalar-data-init.xml
Labels: bug, maintainability
