Repository precice/precice, pull requests merged in 2021-11, with the labels that each got.

#1123 Add support for CMake 3.14 FindPython3
  CMakeLists.txt
  cmake/Validation.cmake
  docs/changelog/1123.md
Labels: usability, maintainability

#1136 Add VTU exporter
  docs/changelog/1136.md
  src/io/config/ExportConfiguration.cpp
  src/io/config/ExportConfiguration.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
Labels: enhancement, usability

#1120 Add SerialTests/Time and SerialTests/InitializeData
  src/precice/tests/SerialTests.cpp
  src/precice/tests/implicit-scalar-data-init.xml
  src/precice/tests/oneway-data-init-read-mapping.xml
  src/precice/tests/oneway-data-init-write-mapping.xml
Labels: maintainability

#1142 Make reformatting options more verbose
  .github/pull_request_template.md
  tools/formatting/check-format
Labels: maintainability
