Repository precice/precice, pull requests merged in 2021-03, with the labels that each got.

#906 Scaled consistent mapping implementation
  .gitignore
  docs/changelog/906.md
  src/mapping/Mapping.cpp
  src/mapping/Mapping.hpp
  src/mapping/NearestNeighborMapping.cpp
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/tests/NearestNeighborMappingTest.cpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/mesh/Triangle.cpp
  src/mesh/Utils.cpp
  src/mesh/Utils.hpp
  src/mesh/tests/MeshTest.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/mapping-scaled-consistent-onA.xml
  src/precice/tests/mapping-scaled-consistent-onB.xml
  src/sources.cmake
Labels: enhancement

#970 Fix FindNumpy use of find_path
  cmake/modules/FindNumPy.cmake
  docs/changelog/970.md
Labels: maintainability

#971 Use mesh::integrate function in watch-integral
  src/precice/impl/WatchIntegral.cpp
  src/precice/impl/WatchIntegral.hpp
Labels: maintainability

#965 Use possibly cached index trees in watch-point
  docs/changelog/965.md
  src/mapping/NearestNeighborMapping.cpp
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/precice/impl/WatchPoint.cpp
  src/precice/impl/WatchPoint.hpp
  src/precice/tests/WatchPointTest.cpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/tests/RTreeTests.cpp
Labels: enhancement, maintainability

#974 Simplify nearest-neighbor computeMapping
  src/mapping/NearestNeighborMapping.cpp
Labels: maintainability

#961 Improve PETSc usability
  docs/changelog/961.md
  src/mapping/PetRadialBasisFctMapping.hpp
  src/utils/Petsc.cpp
  src/utils/Petsc.hpp
Labels: petsc, usability

#983 GitHub actions for macOS CI
  .github/workflows/build-and-test-mac.yml
Labels: building, maintainability

#977 Refactor interpolation functions and clean Query package
  docs/changelog/977.md
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/NearestProjectionMapping.hpp
  src/mapping/Polation.cpp
  src/mapping/Polation.hpp
  src/mapping/tests/PolationTest.cpp
  src/precice/impl/WatchPoint.cpp
  src/precice/impl/WatchPoint.hpp
  src/query/FindClosest.cpp
  src/query/FindClosest.hpp
  src/query/FindClosestEdge.cpp
  src/query/FindClosestEdge.hpp
  src/query/FindClosestTriangle.cpp
  src/query/FindClosestTriangle.hpp
  src/query/FindClosestVertex.cpp
  src/query/FindClosestVertex.hpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/tests/FindClosestTest.cpp
  src/query/tests/FindClosestVertexVisitorTest.cpp
  src/query/tests/RTreeAdapterTests.cpp
  src/query/tests/RTreeTests.cpp
  src/sources.cmake
  src/tests.cmake
Labels: maintainability
