Repository precice/precice, pull requests merged in 2021-01, with the labels that each got.

#925 Fix compiler warnings
  src/mesh/Mesh.cpp
  src/precice/impl/WatchIntegral.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/WatchIntegralTest.cpp
Labels: building

#927 Delete apt/lists/* after apt-get update
  tools/releasing/packaging/docker/Dockerfile
Labels: bug

#931 Use correct function interface in header
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
Labels: bug

#916 Add check for advance timestep size
  docs/changelog/916.md
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: usability

#924 Use repository owner
  .github/workflows/release-docker.yml
Labels: enhancement

#880 Improve Test Log
  docs/changelog/880.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/testing/main.cpp
  src/utils/EigenIO.hpp
Labels: maintainability, usability

#937 Remove a user-side reference to PRECICE_ROOT
  examples/solverdummies/cpp/solverdummy.cpp
Labels: documentation

#941 Clarify error message for checkIfDataIsExchanged
  docs/941.md
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
Labels: usability

#939 Remove obsolete trigger solver plot option
  docs/changelog/939.md
  src/io/ExportContext.hpp
  src/io/config/ExportConfiguration.cpp
  src/io/config/ExportConfiguration.hpp
  src/io/tests/ExportConfigurationTest.cpp
  src/io/tests/config1.xml
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: compatibility

#944 Fix tests not running with Intel MPI
  cmake/CTestConfig.cmake
  docs/changelog/944.md
Labels: bug

#849 Allow multiple mappings to and from the same mesh
  docs/changelog/849.md
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/partition/Partition.hpp
  src/partition/ReceivedPartition.cpp
  src/partition/ReceivedPartition.hpp
  src/partition/tests/ProvidedPartitionTest.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/impl/MeshContext.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/multiple-from-mappings.xml
  src/precice/tests/multiple-to-mappings.xml
Labels: enhancement

#947 Rewrite default PR template, move PR/issue templates.
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
  docs/ISSUE_TEMPLATE.md
  tools/releasing/PULL_REQUEST_TEMPLATE/hotfix_pull_request_template.md
  tools/releasing/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
Labels: maintainability

#940 Deprecate API method getMeshIDs
  docs/940.md
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  src/precice/SolverInterface.hpp
Labels: maintainability

#948 Fix bug in ReceivedPartition
  docs/changelog/948.md
  src/partition/ReceivedPartition.cpp
Labels: bug

#946 Improve error message and improve default setting for zero subvector
  src/acceleration/impl/ResidualSumPreconditioner.cpp
Labels: usability

#951 Fix bug in configuration of Aitken acceleration
  CHANGELOG.md
  src/acceleration/config/AccelerationConfiguration.cpp
  src/precice/tests/SerialTests.cpp
  src/precice/tests/aitken-acceleration.xml
Labels: bug
