Repository precice/precice, pull requests merged in 2022-05, with the labels that each got.

#1249 Remove duplicate documentation.
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
Labels: documentation, maintainability

#1163 Add the support-radius option for Gaussian RBF
  docs/changelog/1163.md
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/impl/BasisFunctions.hpp
  tests/serial/mapping-rbf-gaussian/GaussianShapeParameter.cpp
  tests/serial/mapping-rbf-gaussian/GaussianShapeParameter.xml
  tests/serial/mapping-rbf-gaussian/GaussianSupportRadius.cpp
  tests/serial/mapping-rbf-gaussian/GaussianSupportRadius.xml
  tests/serial/mapping-rbf-gaussian/helpers.cpp
  tests/serial/mapping-rbf-gaussian/helpers.hpp
  tests/tests.cmake
Labels: enhancement

#1285 Fix multiple warnings (in the context of v2.4.0)
  src/cplscheme/CouplingData.hpp
  src/io/ExportXML.cpp
  src/mapping/Mapping.cpp
  src/mesh/Data.hpp
  src/partition/ReceivedPartition.cpp
  src/partition/tests/ReceivedPartitionTest.cpp
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  tests/parallel/UserDefinedMPICommunicatorPetRBF.cpp
  tests/parallel/direct-mesh-access/helpers.cpp
  tests/parallel/direct-mesh-access/helpers.hpp
  tests/serial/initialize-data/helpers.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
Labels: maintainability

#1289 Split communication tests
  src/com/tests/GenericTestFunctions.hpp
  src/com/tests/MPIDirectCommunicationTest.cpp
  src/com/tests/MPIPortsCommunicationTest.cpp
  src/com/tests/MPISinglePortsCommunicationTest.cpp
  src/com/tests/SocketCommunicationTest.cpp
Labels: maintainability

#1287 Refactoring NP mapping with a base class
  src/mapping/BarycentricBaseMapping.cpp
  src/mapping/BarycentricBaseMapping.hpp
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/NearestProjectionMapping.hpp
  src/sources.cmake
Labels: maintainability

#1279 Refactor RBF mappings to have a common base class
  docs/changelog/1279.md
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctBaseMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
  src/sources.cmake
Labels: maintainability

#1295 Fix `isGradientDataRequired` to behave properly
  docs/changelog/1295.md
  src/mesh/Mesh.cpp
  src/precice/impl/Participant.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  tests/serial/mapping-nearest-projection/helpers.cpp
  tests/serial/mapping-rbf-gaussian/helpers.cpp
Labels: bug

#1301 Refactor mapping into consistent and conservative mapping functions
  docs/changelog/1301.md
  src/mapping/BarycentricBaseMapping.cpp
  src/mapping/BarycentricBaseMapping.hpp
  src/mapping/Mapping.cpp
  src/mapping/Mapping.hpp
  src/mapping/NearestNeighborBaseMapping.cpp
  src/mapping/NearestNeighborBaseMapping.hpp
  src/mapping/NearestNeighborGradientMapping.cpp
  src/mapping/NearestNeighborGradientMapping.hpp
  src/mapping/NearestNeighborMapping.cpp
  src/mapping/NearestNeighborMapping.hpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctBaseMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
Labels: maintainability

#1308 Fixes double definition of SolverInterfaceImpl
  tests/serial/mapping-scaled-consistent/helpers.cpp
Labels: bug
