Repository precice/precice, pull requests merged in 2022-04, with the labels that each got.

#1233 Fix missing vtu data pieces in master pvtu file
  docs/changelog/1233.md
  src/io/ExportXML.cpp
  src/io/tests/ExportCSVTest.cpp
  src/io/tests/ExportVTPTest.cpp
  src/io/tests/ExportVTUTest.cpp
Labels: bug

#1246 Fix typos in `docs/`
  docs/documents/020_conventions.dox
  docs/documents/030_optimization.dox
  docs/documents/040_eventtimings.dox
  docs/documents/060_release.dox
  docs/documents/namespaces.dox
  docs/man/man1/testprecice.1
Labels: documentation

#1169 Added API Methods for writing the gradient data needed for Nearest Neighbor Gradient Mapping
  docs/changelog/1169.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/m2n/M2N.cpp
  src/m2n/M2N.hpp
  src/mapping/Mapping.hpp
  src/mapping/NearestNeighborBaseMapping.cpp
  src/mapping/NearestNeighborBaseMapping.hpp
  src/mapping/NearestNeighborGradientMapping.cpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/tests/NearestNeighborGradientMappingTest.cpp
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/config/DataConfiguration.cpp
  src/mesh/config/DataConfiguration.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelScalar.cpp
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelScalar.xml
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelVector.cpp
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadScalar.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadScalar.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadVector.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteScalar.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteScalar.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteVector.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadScalar.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadScalar.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadVector.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadVector.xml
  tests/tests.cmake
Labels: enhancement

#1262 Fix locking in SocketSendQueue
  cmake/CTestConfig.cmake
  docs/changelog/1262.md
  src/com/SocketSendQueue.cpp
  src/com/SocketSendQueue.hpp
Labels: bug

#1242 Move static Index into Mesh
  src/com/tests/GenericTestFunctions.hpp
  src/mapping/NearestNeighborBaseMapping.cpp
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/precice/impl/WatchPoint.cpp
  src/precice/tests/WatchPointTest.cpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/impl/Indexer.cpp
  src/query/impl/Indexer.hpp
  src/query/impl/RTreeAdapter.hpp
  src/query/tests/RTreeTests.cpp
  src/sources.cmake
  src/testing/TestContext.cpp
Labels: maintainability

#1238 Add pkg-config file for binary directory
  CMakeLists.txt
  cmake/binary.pc.in
  cmake/install.pc.in
  docs/changelog/1238.md
Labels: usability

#1263 Upgrade CMake 3.16 logic
  CMakeLists.txt
  cmake/Validation.cmake
  cmake/modules/FindNumPy.cmake
  docs/changelog/1263.md
Labels: building

#1268 Fix GatherScatter bug
  src/m2n/GatherScatterCommunication.cpp
Labels: bug

#1267 Fix wrong `DataContext` for multiple mappings
  docs/changelog/1267.md
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/ReadDataContext.hpp
  src/precice/impl/WriteDataContext.cpp
  src/precice/impl/WriteDataContext.hpp
  src/precice/tests/DataContextTest.cpp
  src/testing/DataContextFixture.cpp
  src/testing/DataContextFixture.hpp
  tests/serial/TestExplicitWithDataMultipleReadWrite.xml
  tests/serial/multiple-mappings/MultipleReadFromMappings.cpp
  tests/serial/multiple-mappings/MultipleReadFromMappings.xml
  tests/serial/multiple-mappings/MultipleReadToMappings.cpp
  tests/serial/multiple-mappings/MultipleReadToMappings.xml
  tests/serial/multiple-mappings/MultipleWriteFromMappings.cpp
  tests/serial/multiple-mappings/MultipleWriteFromMappings.xml
  tests/serial/multiple-mappings/MultipleWriteFromMappingsAndData.cpp
  tests/serial/multiple-mappings/MultipleWriteFromMappingsAndData.xml
  tests/serial/multiple-mappings/MultipleWriteToMappings.cpp
  tests/serial/multiple-mappings/MultipleWriteToMappings.xml
  tests/tests.cmake
Labels: bug
