Repository precice/precice, pull requests merged in 2022-08, with the labels that each got.

#1394 Fix various typos in code documentation
  docs/README.md
  docs/changelog/1338.md
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/MVQNAcceleration.cpp
  src/action/Action.hpp
  src/com/Communication.cpp
  src/io/ExportVTK.cpp
  src/io/ExportXML.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctBaseMapping.hpp
  src/mapping/RadialBasisFctSolver.cpp
  src/mapping/RadialBasisFctSolver.hpp
  src/mapping/impl/BasisFunctions.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/ReadDataContext.hpp
  src/precice/impl/WriteDataContext.hpp
  src/precice/tests/WatchPointTest.cpp
  src/utils/Helpers.hpp
  src/utils/MPI_Mock.hpp
  src/utils/Parallel.cpp
  src/utils/Parallel.hpp
  src/utils/Petsc.hpp
  src/utils/PointerVector.hpp
Labels: documentation

#999 Revive clang-tidy and add GitHub CI
  .clang-tidy
  .github/workflows/code-linting.yml
  CMakeLists.txt
  src/cplscheme/BiCouplingScheme.cpp
  src/mesh/config/DataConfiguration.cpp
  src/precice/impl/ReadDataContext.cpp
  tools/linting/run_clang_tidy.sh
Labels: maintainability, compatibility

#1396 Update third party libs
  docs/changelog/1396.md
  src/com/MPIPortsCommunication.cpp
  src/com/MPISinglePortsCommunication.cpp
  src/com/SocketCommunication.cpp
  src/io/ExportVTK.cpp
  src/io/ExportXML.cpp
  src/mesh/BoundingBox.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/utils/Parallel.hpp
  src/utils/Statistics.hpp
  src/utils/algorithm.hpp
  src/utils/fmtEigen.hpp
  src/utils/fmtSTL.hpp
  src/utils/span.hpp
  thirdparty/fmt/ChangeLog.rst
  thirdparty/fmt/include/fmt/args.h
  thirdparty/fmt/include/fmt/chrono.h
  thirdparty/fmt/include/fmt/color.h
  thirdparty/fmt/include/fmt/compile.h
  thirdparty/fmt/include/fmt/core.h
  thirdparty/fmt/include/fmt/format-inl.h
  thirdparty/fmt/include/fmt/format.h
  thirdparty/fmt/include/fmt/os.h
  thirdparty/fmt/include/fmt/ostream.h
  thirdparty/fmt/include/fmt/printf.h
  thirdparty/fmt/include/fmt/ranges.h
  thirdparty/fmt/include/fmt/std.h
  thirdparty/fmt/include/fmt/xchar.h
  thirdparty/json/include/nlohmann/json.hpp
Labels: dependencies

#1398 Improve revision detection
  cmake/cmake_refresh_git_revision.cmake
  docs/changelog/1398.md
Labels: usability

#1395 Fix the triangle distance calculation
  src/mapping/LinearCellInterpolationMapping.cpp
  src/mapping/NearestNeighborBaseMapping.cpp
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/Polation.cpp
  src/mapping/Polation.hpp
  src/mapping/tests/PolationTest.cpp
  src/precice/impl/WatchPoint.cpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/tests/RTreeAdapterTests.cpp
  src/query/tests/RTreeTests.cpp
Labels: bug

#1406 Add a success statement to the config check
  docs/changelog/1406.md
  src/precice/Tooling.cpp
Labels: usability

#1403 Simplify signature of actions and remove ScaleByDtAction
  docs/changelog/1403.md
  src/action/Action.hpp
  src/action/ComputeCurvatureAction.cpp
  src/action/ComputeCurvatureAction.hpp
  src/action/PythonAction.cpp
  src/action/PythonAction.hpp
  src/action/PythonAction.py
  src/action/RecorderAction.cpp
  src/action/RecorderAction.hpp
  src/action/ScaleByAreaAction.cpp
  src/action/ScaleByAreaAction.hpp
  src/action/ScaleByDtAction.cpp
  src/action/ScaleByDtAction.hpp
  src/action/SummationAction.cpp
  src/action/SummationAction.hpp
  src/action/config/ActionConfiguration.cpp
  src/action/config/ActionConfiguration.hpp
  src/action/tests/PythonActionTest.cpp
  src/action/tests/ScaleActionTest-testConfiguration-3.xml
  src/action/tests/ScaleActionTest-testConfiguration-4.xml
  src/action/tests/ScaleActionTest.cpp
  src/action/tests/SummationActionTest.cpp
  src/action/tests/TestAllAction.py
  src/action/tests/TestOmitAction1.py
  src/action/tests/TestOmitAction2.py
  src/action/tests/TestOmitAction3.py
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/sources.cmake
Labels: maintainability, breaking change

#1409 Link to parallel solver dummies
  examples/solverdummies/README.md
Labels: documentation

#1413 Upgrade preCICE C++ standard to C++17
  .github/pull_request_template.md
  CMakeLists.txt
  docs/changelog/1413.md
Labels: compatibility

#1412 Update release workflow to consider target OS for packages
  .github/workflows/release.yml
  tools/releasing/PULL_REQUEST_TEMPLATE/hotfix_pull_request_template.md
  tools/releasing/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
Labels: maintainability

#1372 Apply Cholesky decomposition for s.p.d. mapping matrices
  docs/changelog/1372.md
  src/mapping/RadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctSolver.cpp
  src/mapping/RadialBasisFctSolver.hpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/sources.cmake
  tests/serial/mapping-rbf-gaussian/GaussianShapeParameter.xml
  tests/serial/mapping-rbf-gaussian/GaussianSupportRadius.xml
  tests/serial/mapping-rbf-gaussian/helpers.cpp
Labels: enhancement

#1378 Add Wendland C2 and C4 RBF functions
  docs/changelog/1378.md
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
Labels: enhancement
