Repository precice/precice, pull requests merged in 2022-06, with the labels that each got.

#1297 [V2] Added "Volume Cell Interpolation" mapping support in 2D
  docs/changelog/1297.md
  src/mapping/LinearCellInterpolationMapping.cpp
  src/mapping/LinearCellInterpolationMapping.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/tests/LinearCellInterpolationMappingTest.cpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/sources.cmake
  src/tests.cmake
  tests/parallel/mapping-volume/ParallelSquare1To2.cpp
  tests/parallel/mapping-volume/ParallelSquare1To2.xml
  tests/parallel/mapping-volume/ParallelSquare2To1.cpp
  tests/parallel/mapping-volume/ParallelSquare2To1.xml
  tests/parallel/mapping-volume/ParallelSquareConservative1To2.cpp
  tests/parallel/mapping-volume/ParallelSquareConservative1To2.xml
  tests/parallel/mapping-volume/ParallelTriangleConservative2To1.cpp
  tests/parallel/mapping-volume/ParallelTriangleConservative2To1.xml
  tests/serial/mapping-volume/OneTriangleConservativeRead.cpp
  tests/serial/mapping-volume/OneTriangleConservativeRead.xml
  tests/serial/mapping-volume/OneTriangleConservativeWrite.cpp
  tests/serial/mapping-volume/OneTriangleConservativeWrite.xml
  tests/serial/mapping-volume/OneTriangleRead.cpp
  tests/serial/mapping-volume/OneTriangleRead.xml
  tests/serial/mapping-volume/OneTriangleWrite.cpp
  tests/serial/mapping-volume/OneTriangleWrite.xml
  tests/serial/mapping-volume/helpers.cpp
  tests/serial/mapping-volume/helpers.hpp
  tests/tests.cmake
Labels: enhancement

#1319 Extract RBF solver into a separate class
  docs/changelog/1319.md
  src/mapping/RadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctSolver.hpp
  src/sources.cmake
  src/utils/EigenHelperFunctions.cpp
  src/utils/EigenHelperFunctions.hpp
Labels: compatibility

#1320 Speed-up RBF matrix assembly
  docs/changelog/1320.md
  src/mapping/RadialBasisFctSolver.hpp
Labels: enhancement

#1315 Add output support for gradient data
  docs/changelog/1315.md
  src/io/ExportVTK.cpp
  src/io/ExportVTK.hpp
  src/io/tests/ExportVTKTest.cpp
Labels: enhancement

#1332 Add default interface for BSD flavors
  docs/changelog/1332.md
  src/utils/networking.cpp
Labels: bug

#1338 Improve basis function implementation
  docs/changelog/1338.md
  src/mapping/impl/BasisFunctions.hpp
  src/math/math.hpp
  src/math/tests/MathTest.cpp
  src/tests.cmake
Labels: enhancement

#1339 Make areas of triangles positive in 2D + Removed dead code
  src/math/geometry.cpp
  src/math/geometry.hpp
  src/math/tests/GeometryTest.cpp
Labels: maintainability

#1344 Add option to disable precice-tools building
  CMakeLists.txt
  cmake/CTestConfig.cmake
Labels: building

#1341 Extend warning about MPI ports with OpenMPI
  src/m2n/config/M2NConfiguration.cpp
Labels: usability
