Repository precice/precice, pull requests merged in 2022-12, with the labels that each got.

#1497 Use central object library
  CMakeLists.txt
  extras/bindings/c/CMakeLists.txt
  extras/bindings/fortran/CMakeLists.txt
  src/sources.cmake
  tools/building/updateSourceFiles.py
Labels: building

#1499 Remove the ability to install tests
  CMakeLists.txt
  docs/changelog/1499.md
  docs/man/man1/testprecice.1
Labels: building, breaking change

#1462 Simplify compositional couplingscheme
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  tests/serial/circular/Explicit.cpp
  tests/serial/circular/Explicit.xml
  tests/serial/circular/helper.hpp
  tests/serial/three-solvers/ThreeSolversImplicitImplicit.cpp
  tests/serial/three-solvers/ThreeSolversImplicitImplicit.xml
  tests/tests.cmake
Labels: breaking change

#1508 Change CPL actions to enum struct
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/Constants.cpp
  src/cplscheme/Constants.hpp
  src/cplscheme/CouplingScheme.cpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: maintainability

#1503 Remove second order extrapolation.
  docs/changelog/1503.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/impl/Extrapolation.cpp
  src/cplscheme/tests/ExtrapolationTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  tests/serial/multi-coupling/MultiCoupling.xml
Labels: maintainability
