Repository precice/precice, pull requests merged in 2022-07, with the labels that each got.

#1307 Fix first participant method in compositional cplscheme
  docs/changelog/1307.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  tests/serial/three-solvers/ThreeSolversFirstParticipant.cpp
  tests/serial/three-solvers/ThreeSolversFirstParticipant.xml
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataFirstParticipant.cpp
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataFirstParticipant.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipant.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipant.xml
  tests/tests.cmake
Labels: bug

#1222 Remove mapWriteDataFrom and mapReadDataTo
  docs/changelog/1222.md
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  tests/serial/stationary-mapping-with-solver-mesh/StationaryMappingWithSolverMesh2D.xml
  tests/serial/stationary-mapping-with-solver-mesh/StationaryMappingWithSolverMesh3D.xml
  tests/serial/stationary-mapping-with-solver-mesh/helpers.cpp
  tests/serial/stationary-mapping-with-solver-mesh/helpers.hpp
  tests/tests.cmake
Labels: breaking change

#1362 Remove isReadDataAvailable and isWriteDataRequired
  docs/changelog/1362.md
  examples/solverdummies/c/solverdummy.c
  examples/solverdummies/cpp/solverdummy.cpp
  examples/solverdummies/fortran/solverdummy.f90
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  tests/parallel/quasi-newton/helpers.cpp
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirstNoInit.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
Labels: usability, maintainability, breaking change

#1350 Merge initializeData() into initialize()
  docs/changelog/1350.md
  examples/solverdummies/fortran/solverdummy.f90
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
  src/action/Action.hpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  tests/serial/TestExplicitWithDataMultipleReadWrite.cpp
  tests/serial/TestReadAPI.cpp
  tests/serial/action-timings/ActionTimingsExplicit.cpp
  tests/serial/action-timings/ActionTimingsImplicit.cpp
  tests/serial/initialize-data/Explicit.cpp
  tests/serial/initialize-data/Implicit.cpp
  tests/serial/initialize-data/helpers.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadScalar.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadVector.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteScalar.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteVector.cpp
  tests/serial/three-solvers/helpers.cpp
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirstNoInit.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
Labels: usability, breaking change

#1368 Allow initialize=true all data in serial coupling scheme
  docs/changelog/1367.md
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/impl/Participant.cpp
  src/precice/impl/Participant.hpp
  tests/serial/initialize-data/ImplicitBoth.cpp
  tests/serial/initialize-data/ImplicitBoth.xml
  tests/tests.cmake
Labels: usability, breaking change

#1340 Add gradient data to xml exporters
  docs/changelog/1340.md
  src/io/ExportXML.cpp
  src/io/ExportXML.hpp
  src/io/tests/ExportVTPTest.cpp
  src/io/tests/ExportVTUTest.cpp
Labels: enhancement

#1371 Configure gradient data requirement automatically
  docs/changelog/1371.md
  src/io/tests/ExportVTKTest.cpp
  src/io/tests/ExportVTPTest.cpp
  src/io/tests/ExportVTUTest.cpp
  src/mapping/Mapping.cpp
  src/mapping/Mapping.hpp
  src/mapping/NearestNeighborBaseMapping.cpp
  src/mapping/NearestNeighborGradientMapping.cpp
  src/mapping/tests/NearestNeighborGradientMappingTest.cpp
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/config/DataConfiguration.cpp
  src/mesh/config/DataConfiguration.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/MappingContext.hpp
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelScalar.cpp
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelScalar.xml
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelVector.cpp
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelVector.xml
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelWriteVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadScalar.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadScalar.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteScalar.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteVector.cpp
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalWriteVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadBlockVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadScalar.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestUnidirectionalReadVector.xml
  tests/serial/mapping-nearest-neighbor-gradient/helpers.cpp
Labels: enhancement, usability

#1383 Add hint for send/receive errors (sockets)
  src/com/SocketCommunication.cpp
Labels: usability

#1224 WIP: Deprecate isReadDataAvailable and isWriteDataRequired
  docs/changelog/1224.md
  src/precice/SolverInterface.hpp
Labels: compatibility
