Repository precice/precice, pull requests merged in 2022-03, with the labels that each got.

#1208 Fix issues with the legacy API of boost test
  src/testing/main.cpp
Labels: bug

#1209 Simplify boost test setup
  src/testing/GlobalFixtures.cpp
  src/testing/main.cpp
  src/tests.cmake
Labels: maintainability

#1210 Fix format-all-docker modifying file owner
  docs/changelog/1210.md
  tools/formatting/format-all-docker
Labels: bug, maintainability

#1212 Fixed outdated documentation
  src/mesh/Triangle.hpp
Labels: documentation

#1215 Refactor cplscheme tests
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/explicit-coupling-scheme-1.xml
  src/cplscheme/tests/explicit-coupling-scheme-2.xml
  src/cplscheme/tests/multi-solver-coupling-1.xml
  src/cplscheme/tests/multi-solver-coupling-2.xml
  src/cplscheme/tests/multi-solver-coupling-3.xml
  src/cplscheme/tests/multi-solver-coupling-4.xml
  src/cplscheme/tests/parallel-explicit-coupling-datainit.xml
  src/cplscheme/tests/parallel-implicit-cplscheme-relax-const-config.xml
  src/cplscheme/tests/serial-explicit-coupling-datainit.xml
  src/cplscheme/tests/serial-implicit-cplscheme-absolute-config.xml
  src/cplscheme/tests/serial-implicit-cplscheme-relax-const-config.xml
Labels: maintainability

#1216 Simplify implementation of data mapping in SolverInterfaceImpl
  docs/changelog/1216.md
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/tests/DataContextTest.cpp
  src/testing/DataContextFixture.cpp
  src/testing/DataContextFixture.hpp
  src/tests.cmake
Labels: maintainability

#1220 Fix doxygen and source comments in `src/`
  docs/changelog/1120.md
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/BroydenAcceleration.hpp
  src/acceleration/IQNILSAcceleration.hpp
  src/acceleration/MVQNAcceleration.cpp
  src/acceleration/MVQNAcceleration.hpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/impl/QRFactorization.hpp
  src/acceleration/impl/ResidualSumPreconditioner.cpp
  src/acceleration/impl/SVDFactorization.hpp
  src/action/RecorderAction.hpp
  src/com/Communication.hpp
  src/com/MPISinglePortsCommunication.cpp
  src/com/MPISinglePortsCommunication.hpp
  src/com/SocketCommunication.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/impl/ConvergenceMeasure.hpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/io/TXTTableWriter.cpp
  src/io/config/ExportConfiguration.cpp
  src/logging/LogConfiguration.cpp
  src/logging/Logger.hpp
  src/m2n/M2N.hpp
  src/m2n/config/M2NConfiguration.cpp
  src/mapping/Mapping.hpp
  src/mapping/NearestNeighborBaseMapping.cpp
  src/mapping/PetRadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctMapping.hpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/mapping/tests/PetRadialBasisFctMappingTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/math/geometry.cpp
  src/math/geometry.hpp
  src/mesh/Mesh.cpp
  src/mesh/Utils.hpp
  src/mesh/config/DataConfiguration.hpp
  src/mesh/tests/MeshTest.cpp
  src/partition/ReceivedPartition.cpp
  src/partition/ReceivedPartition.hpp
  src/partition/tests/ProvidedPartitionTest.cpp
  src/precice/SolverInterface.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/impl/ValidationMacros.hpp
  src/precice/tests/ParallelTests.cpp
  src/precice/tests/SerialTests.cpp
  src/query/impl/RTreeAdapter.hpp
  src/testing/GlobalFixtures.cpp
  src/testing/TestContext.hpp
  src/testing/Testing.hpp
  src/utils/EventUtils.hpp
  src/utils/TypeNames.hpp
  src/utils/fmt.hpp
  src/utils/tests/AlgorithmTest.cpp
  src/xml/Printer.cpp
Labels: documentation

#1226 Improved edge barycentric coordinates computation
  src/math/barycenter.cpp
Labels: maintainability
