Repository precice/precice, pull requests merged in 2022-11, with the labels that each got.

#1455 Remove incorrect warning for waveform order zero and serial coupling schemes
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
Labels: bug

#1467 Check for duplicate exchange tags
  docs/changelog/1467.md
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
Labels: bug

#1464 Extend docs of isTimeWindowComplete
  src/precice/SolverInterface.hpp
Labels: documentation

#1420 Improve compatibility with applications using Boost.Log
  src/logging/LogConfiguration.cpp
  src/logging/LogConfiguration.hpp
  src/logging/Logger.cpp
  src/logging/Logger.hpp
  src/logging/config/LogConfiguration.cpp
Labels: bug, usability

#1351 Changed NP behavior for some edge cases
  docs/changelog/1351.md
  src/mapping/tests/LinearCellInterpolationMappingTest.cpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/query/Index.cpp
  src/query/Index.hpp
Labels: bug

#1452 Add CMake presets
  .gitignore
  CMakePresets.json
Labels: building

#1486 Fix include path for eigen unsupported
  src/time/Waveform.cpp
Labels: bug

#1322 Vertex-only API
  docs/changelog/1322.md
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
  src/mapping/tests/PolationTest.cpp
  src/mesh/Edge.cpp
  src/mesh/Edge.hpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/Tetrahedron.cpp
  src/mesh/Tetrahedron.hpp
  src/mesh/Triangle.cpp
  src/mesh/Triangle.hpp
  src/mesh/tests/EdgeTest.cpp
  src/mesh/tests/MeshTest.cpp
  src/mesh/tests/TetrahedronTest.cpp
  src/mesh/tests/TriangleTest.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/query/tests/RTreeTests.cpp
  src/testing/Testing.cpp
  tests/parallel/NearestProjectionRePartitioning.cpp
  tests/parallel/mapping-volume/ParallelSquare1To2.cpp
  tests/parallel/mapping-volume/ParallelSquare2To1.cpp
  tests/parallel/mapping-volume/ParallelSquareConservative1To2.cpp
  tests/parallel/mapping-volume/ParallelTriangleConservative2To1.cpp
  tests/serial/TestExplicitWithSolverGeometry.cpp
  tests/serial/mapping-nearest-projection/MappingNearestProjectionEdges.cpp
  tests/serial/mapping-nearest-projection/MappingNearestProjectionEdges.xml
  tests/serial/mapping-nearest-projection/MappingNearestProjectionExplicitEdges.cpp
  tests/serial/mapping-nearest-projection/MappingNearestProjectionImplicitEdges.cpp
  tests/serial/mapping-nearest-projection/QuadMappingDiagonalNearestProjectionEdgesTallKite.cpp
  tests/serial/mapping-nearest-projection/QuadMappingDiagonalNearestProjectionEdgesTallKite.xml
  tests/serial/mapping-nearest-projection/QuadMappingDiagonalNearestProjectionEdgesWideKite.cpp
  tests/serial/mapping-nearest-projection/QuadMappingDiagonalNearestProjectionEdgesWideKite.xml
  tests/serial/mapping-nearest-projection/QuadMappingNearestProjectionEdges.cpp
  tests/serial/mapping-nearest-projection/QuadMappingNearestProjectionEdges.xml
  tests/serial/mapping-nearest-projection/helpers.cpp
  tests/serial/mapping-nearest-projection/helpers.hpp
  tests/serial/mapping-nearest-projection/testQuadMappingDiagonalNearestProjectionImplicitEdgesTallKite.cpp
  tests/serial/mapping-nearest-projection/testQuadMappingDiagonalNearestProjectionImplicitEdgesTallKite.xml
  tests/serial/mapping-nearest-projection/testQuadMappingDiagonalNearestProjectionImplicitEdgesWideKite.cpp
  tests/serial/mapping-nearest-projection/testQuadMappingDiagonalNearestProjectionImplicitEdgesWideKite.xml
  tests/serial/mapping-nearest-projection/testQuadMappingNearestProjectionExplicitEdges.xml
  tests/serial/mapping-nearest-projection/testQuadMappingNearestProjectionImplicitEdges.cpp
  tests/serial/mapping-nearest-projection/testQuadMappingNearestProjectionImplicitEdges.xml
  tests/serial/mapping-scaled-consistent/helpers.cpp
  tests/serial/mapping-volume/helpers.cpp
  tests/tests.cmake
Labels: usability, breaking change
