Repository precice/precice, pull requests merged in 2022-09, with the labels that each got.

#1430 Add version info of dependencies
  CMakeLists.txt
  docs/changelog/1430.md
Labels: usability

#1435 Simplify implementation of DataContext.
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/MappingContext.hpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/ReadDataContext.hpp
  src/precice/impl/WriteDataContext.cpp
  src/precice/impl/WriteDataContext.hpp
  src/testing/DataContextFixture.cpp
Labels: maintainability

#1422 Simplify waveform class: Don't use data from old window, allow higher-order interpolation through BSplines
  docs/changelog/1422.md
  src/sources.cmake
  src/testing/WaveformFixture.cpp
  src/testing/WaveformFixture.hpp
  src/tests.cmake
  src/time/Storage.cpp
  src/time/Storage.hpp
  src/time/Time.cpp
  src/time/Waveform.cpp
  src/time/Waveform.hpp
  src/time/tests/StorageTest.cpp
  src/time/tests/WaveformTest.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingZero.xml
Labels: enhancement

#1442 Improve encapsulation of CouplingData
  src/acceleration/Acceleration.hpp
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/IQNILSAcceleration.cpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
Labels: maintainability
