Repository precice/precice, pull requests merged in 2023-07, with the labels that each got.

#1704 Fix bug that prevents requiring checkpoint in last window
  src/cplscheme/BaseCouplingScheme.cpp
  tests/serial/ImplicitCheckpointing.cpp
  tests/serial/ImplicitCheckpointing.xml
  tests/tests.cmake
Labels: bug

#1714 Make Waveform accessible from CouplingData and rename `waveform-order` to `waveform-degree`
  docs/changelog/1714.md
  src/com/SerializedStamples.cpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/mesh/config/DataConfiguration.cpp
  src/mesh/config/DataConfiguration.hpp
  src/mesh/config/MeshConfiguration.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/impl/ParticipantState.cpp
  src/precice/impl/ParticipantState.hpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/ReadDataContext.hpp
  src/sources.cmake
  src/testing/WaveformFixture.cpp
  src/time/SharedPointer.hpp
  src/time/Time.cpp
  src/time/Time.hpp
  src/time/Waveform.cpp
  src/time/Waveform.hpp
  src/time/tests/WaveformTest.cpp
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingThird.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingThird.xml
Labels: enhancement, breaking change

#1719 Fix initialization for `substeps="false"`
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcyclingNoSubstepsUseInitFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcyclingNoSubstepsUseInitFirst.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcyclingNoSubstepsUseInitFirst.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcyclingNoSubstepsUseInitFirst.xml
  tests/tests.cmake
Labels: bug

#1738 Remove extrapolation
  docs/1738.md
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/com/tests/SerializedStamplesTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/cplscheme/CouplingScheme.cpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/time/Storage.cpp
  src/time/Storage.hpp
  src/time/tests/StorageTest.cpp
  tests/serial/multi-coupling/MultiCoupling.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirstExtrapolation.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirstExtrapolation.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingFirstExtrapolation.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingFirstExtrapolation.xml
  tests/tests.cmake
Labels: breaking change

#1741 Remove hasMesh and hasData.
  docs/changelog/1741.md
  extras/bindings/c/include/precice/preciceC.h
  extras/bindings/c/src/preciceC.cpp
  extras/bindings/fortran/include/precice/preciceFortran.hpp
  extras/bindings/fortran/src/preciceFortran.cpp
  src/precice/Participant.cpp
  src/precice/Participant.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
  tests/serial/explicit/helpers.cpp
  tests/serial/mapping-volume/OneTetraRead.cpp
  tests/serial/mapping-volume/OneTetraWrite.cpp
  tests/serial/mapping-volume/OneTriangleRead.cpp
  tests/serial/mapping-volume/OneTriangleWrite.cpp
  tests/serial/mapping-volume/helpers.cpp
  tests/serial/mapping-volume/helpers.hpp
Labels: breaking change

#1750 Remove non-empty precice-run when running tests
  src/testing/main.cpp
Labels: maintainability

#1697 Fix DivByZero for scaled constraints
  docs/changelog/1697.md
  src/mapping/Mapping.cpp
  src/mapping/tests/NearestNeighborMappingTest.cpp
Labels: bug

#1740 Make direct access non-experimental
  docs/changelog/1740.md
  extras/bindings/c/include/precice/preciceC.h
  extras/bindings/c/src/preciceC.cpp
  extras/bindings/fortran/include/precice/preciceFortran.hpp
  extras/bindings/fortran/src/preciceFortran.cpp
  src/precice/Participant.cpp
  src/precice/Participant.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
  tests/parallel/direct-mesh-access/AccessReceivedMeshAndMapping.cpp
  tests/parallel/direct-mesh-access/AccessReceivedMeshAndMapping.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshEmptyPartition.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshEmptyPartitionTwoLevelInit.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshNoOverlap.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshNoOverlapTwoLevelInit.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshOverlap.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshOverlapNoWrite.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshOverlapNoWriteTwoLevelInit.xml
  tests/parallel/direct-mesh-access/AccessReceivedMeshOverlapTwoLevelInit.xml
  tests/parallel/direct-mesh-access/helpers.cpp
  tests/serial/direct-mesh-access/DirectAccessReadWrite.cpp
  tests/serial/direct-mesh-access/DirectAccessReadWrite.xml
  tests/serial/direct-mesh-access/DirectAccessWithDataInitialization.cpp
  tests/serial/direct-mesh-access/DirectAccessWithDataInitialization.xml
  tests/serial/direct-mesh-access/DirectAccessWithWaveform.cpp
  tests/serial/direct-mesh-access/DirectAccessWithWaveform.xml
  tests/serial/direct-mesh-access/Explicit.cpp
  tests/serial/direct-mesh-access/Explicit.xml
  tests/serial/direct-mesh-access/ExplicitAndMapping.cpp
  tests/serial/direct-mesh-access/ExplicitAndMapping.xml
  tests/serial/direct-mesh-access/ExplicitRead.cpp
  tests/serial/direct-mesh-access/ExplicitRead.xml
  tests/serial/direct-mesh-access/Implicit.cpp
  tests/serial/direct-mesh-access/Implicit.xml
Labels: breaking change
