Repository precice/precice, pull requests merged in 2023-04, with the labels that each got.

#1615 Fix directories when used as subproject
  CMakeLists.txt
  cmake/CTestConfig.cmake
  cmake/PrintHelper.cmake
  cmake/cmake_refresh_git_revision.cmake
  cmake/cmake_uninstall.cmake.in
  docs/changelog/1615.md
  src/sources.cmake
  tools/building/updateSourceFiles.py
Labels: bug

#1614 Cleanup actions
  docs/changelog/1614.md
  src/action/Action.hpp
  src/action/ComputeCurvatureAction.cpp
  src/action/ComputeCurvatureAction.hpp
  src/action/PythonAction.cpp
  src/action/PythonAction.hpp
  src/action/PythonAction.py
  src/action/config/ActionConfiguration.cpp
  src/action/config/ActionConfiguration.hpp
  src/action/tests/PythonActionTest.cpp
  src/action/tests/ScaleActionTest-testConfiguration-1.xml
  src/action/tests/ScaleActionTest-testConfiguration-2.xml
  src/action/tests/SummationActionTest-testConfiguration-1.xml
  src/action/tests/SummationActionTest.cpp
  src/action/tests/TestAction.py
  src/action/tests/TestAllAction.py
  src/action/tests/TestDeprecatedAction.py
  src/action/tests/TestOmitAction1.py
  src/action/tests/TestOmitAction2.py
  src/action/tests/TestOmitAction3.py
  src/precice/impl/SolverInterfaceImpl.cpp
  src/sources.cmake
  tests/serial/SummationActionTwoSources.xml
  tests/serial/action-timings/ActionTimingsExplicit.cpp
  tests/serial/action-timings/ActionTimingsExplicit.xml
  tests/serial/action-timings/ActionTimingsImplicit.cpp
  tests/serial/action-timings/ActionTimingsImplicit.xml
  tests/serial/whitebox/TestConfigurationComsol.xml
  tests/serial/whitebox/TestConfigurationPeano.xml
  tests/serial/whitebox/TestExplicitWithDataScaling.xml
Labels: maintainability, breaking change

#1621 Add check for C++17 std::transform_reduce
  CMakeLists.txt
  cmake/CheckCXX11Library.cmake
  cmake/CheckSTL.cmake
Labels: building

#1628 Fix timestep vs. time step.
  extras/bindings/c/include/precice/SolverInterfaceC.h
  extras/bindings/c/src/SolverInterfaceC.cpp
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/cplscheme.dox
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
  src/precice/precice.dox
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/serial-coupling/DoNothingWithSubcycling.cpp
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithWaveform.cpp
  tests/serial/time/implicit/multi-coupling/DoNothingWithSubcycling.cpp
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirstNoInit.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingFirstNoInit.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingZero.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingFirst.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingZero.cpp
Labels: documentation

#1624 Change `IDs` in Fortran bindings to `ids`
  docs/changelog/1624.md
  extras/bindings/fortran/include/precice/SolverInterfaceFortran.hpp
  extras/bindings/fortran/src/SolverInterfaceFortran.cpp
Labels: breaking change
