Repository precice/precice, pull requests merged in 2023-05, with the labels that each got.

#1638 Update fmt to 9.1
  docs/changelog/1638.md
  thirdparty/fmt/include/fmt/chrono.h
  thirdparty/fmt/include/fmt/color.h
  thirdparty/fmt/include/fmt/compile.h
  thirdparty/fmt/include/fmt/core.h
  thirdparty/fmt/include/fmt/format-inl.h
  thirdparty/fmt/include/fmt/format.h
  thirdparty/fmt/include/fmt/ostream.h
  thirdparty/fmt/include/fmt/ranges.h
  thirdparty/fmt/include/fmt/std.h
  thirdparty/fmt/include/fmt/xchar.h
Labels: dependencies

#1640 Refactor mesh vertex id checks
  src/mesh/Utils.hpp
  src/mesh/tests/UtilsTest.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/WriteDataContext.cpp
  src/tests.cmake
Labels: maintainability

#1633 Introduce Wrappers for better encapsulation of Read/WriteDataContext
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/WriteDataContext.cpp
  src/precice/impl/WriteDataContext.hpp
Labels: maintainability

#1653 Add event histogram to precice-events
  tools/profiling/precice-events
Labels: enhancement

#1612 Add write data buffer
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/action/PythonAction.cpp
  src/action/ScaleByAreaAction.cpp
  src/action/SummationAction.cpp
  src/action/tests/PythonActionTest.cpp
  src/action/tests/ScaleActionTest.cpp
  src/action/tests/SummationActionTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/impl/Extrapolation.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/mesh/Mesh.hpp
  src/precice/impl/DataContext.cpp
  src/precice/impl/DataContext.hpp
  src/precice/impl/MappingContext.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/ReadDataContext.hpp
  src/precice/impl/WriteDataContext.cpp
  src/precice/impl/WriteDataContext.hpp
  src/precice/tests/DataContextTest.cpp
  src/sources.cmake
  src/testing/WaveformFixture.cpp
  src/time/Sample.hpp
  src/time/Stample.hpp
  src/time/Storage.cpp
  src/time/Storage.hpp
  src/time/Waveform.cpp
  src/time/Waveform.hpp
  src/time/tests/StorageTest.cpp
  src/time/tests/WaveformTest.cpp
  tests/serial/action-timings/ActionTimingsExplicit.cpp
  tests/serial/action-timings/ActionTimingsImplicit.cpp
Labels: maintainability

#1661 Fix events tests for Python 3.10
  tools/profiling/precice-events
Labels: bug

#1674 Fix incorrect write gradient data C API
  extras/bindings/c/src/ParticipantC.cpp
Labels: bug
