Repository precice/precice, pull requests merged in 2023-02, with the labels that each got.

#1495 Consistently implement `BoundingBox`
  docs/changelog/1495.md
  src/mesh/BoundingBox.cpp
  src/mesh/BoundingBox.hpp
  src/mesh/Mesh.cpp
  src/mesh/tests/BoundingBoxTest.cpp
Labels: maintainability

#1574 Add missing xml error handlers
  docs/changelog/1574.md
  src/logging/LogConfiguration.cpp
  src/xml/ConfigParser.cpp
Labels: bug

#1575 Remove method attribute for parallel cplschemes
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/tests/parallel-explicit-coupling-datainit.xml
Labels: usability

#1538 Optional stacktrace generation with libbacktrace
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  thirdparty/libbacktrace/CMakeLists.txt
  thirdparty/libbacktrace/libbacktrace.tar.gz
  thirdparty/libbacktrace/libbacktrace.zip
  thirdparty/libbacktrace/update.sh
Labels: building

#1526 Fix incorrect read data in watch integral test
  tests/serial/watch-integral/WatchIntegralScaleAndNoScale.cpp
  tests/serial/watch-integral/WatchIntegralScaleAndNoScale.xml
Labels: bug
