Repository precice/precice, pull requests merged in 2023-03, with the labels that each got.

#1587 Remove getMeshIDs
  src/precice/SolverInterface.cpp
  src/precice/SolverInterface.hpp
  src/precice/impl/SolverInterfaceImpl.cpp
  src/precice/impl/SolverInterfaceImpl.hpp
Labels: breaking change

#1586 Remove getThisTimeWindowRemainder(), use getNextTimestepMaxLength() instead
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/precice/impl/SolverInterfaceImpl.cpp
Labels: maintainability

#1578 Fix PETSc mappings crashing when checking the config
  docs/changelog/1578.md
  src/precice/Tooling.cpp
  src/utils/Parallel.cpp
  src/utils/Parallel.hpp
Labels: bug

#1576 Add attribute hints
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/xml/XMLTag.cpp
  src/xml/XMLTag.hpp
Labels: usability

#1592 Add error for initializing directly-accessed data
  docs/changelog/1592.md
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  tests/serial/direct-mesh-access/DirectAccessWithDataInitialization.cpp
  tests/serial/direct-mesh-access/DirectAccessWithDataInitialization.xml
Labels: bug

#1593 Fix info log for linear-cell interpolation mapping
  src/mapping/LinearCellInterpolationMapping.cpp
Labels: usability

#1606 Print all reasonable tag hints instead of only the first
  src/xml/ConfigParser.cpp
  src/xml/XMLTag.cpp
Labels: usability

#1483 Add partition of unity RBF data mapping
  docs/changelog/1483.md
  src/mapping/PartitionOfUnityMapping.hpp
  src/mapping/RadialBasisFctSolver.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/impl/CreateClustering.hpp
  src/mapping/impl/SphericalVertexCluster.hpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/mapping/tests/PartitionOfUnityClusteringTest.cpp
  src/mapping/tests/PartitionOfUnityMappingTest.cpp
  src/mapping/tests/mapping-rbf-pum-direct-config.xml
  src/mesh/BoundingBox.cpp
  src/mesh/BoundingBox.hpp
  src/mesh/tests/BoundingBoxTest.cpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/tests/RTreeTests.cpp
  src/sources.cmake
  src/tests.cmake
Labels: enhancement

#1609 Disable copy-constructor for ReadDataContext and WriteDataContext.
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/precice/impl/Participant.hpp
  src/precice/impl/ReadDataContext.hpp
  src/precice/impl/WriteDataContext.hpp
Labels: maintainability
