Repository precice/precice, pull requests merged in 2023-10, with the labels that each got.

#1805 Compute bounding box for pum clustering locally
  docs/changelog/1805.md
  src/mapping/PartitionOfUnityMapping.hpp
  src/mapping/impl/CreateClustering.hpp
  src/mesh/BoundingBox.cpp
  src/mesh/Mesh.hpp
  src/query/Index.cpp
  src/query/Index.hpp
  src/query/tests/RTreeTests.cpp
Labels: bug

#1721 Add error, if `substeps="true"` for unsupported acceleration scheme.
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  tests/quasi-newton/parallel/TestQN1.xml
  tests/quasi-newton/parallel/TestQN1EmptyPartition.xml
  tests/quasi-newton/parallel/TestQN2.xml
  tests/quasi-newton/parallel/TestQN2EmptyPartition.xml
  tests/quasi-newton/parallel/TestQN3.xml
  tests/quasi-newton/parallel/TestQN3EmptyPartition.xml
  tests/quasi-newton/parallel/TestQN4.xml
  tests/quasi-newton/parallel/TestQN4EmptyPartition.xml
  tests/quasi-newton/serial/DefaultConfig.xml
  tests/quasi-newton/serial/TestQN1.xml
  tests/quasi-newton/serial/TestQN2.xml
  tests/quasi-newton/serial/TestQN3.xml
  tests/quasi-newton/serial/TestQN4.xml
  tests/serial/AitkenAcceleration.xml
  tests/serial/PreconditionerBug.xml
  tests/serial/multi-coupling/MultiCoupling.xml
Labels: usability

#1837 Do not interpolate data for existing timestamps
  docs/changelog/1837.md
  src/time/Storage.cpp
  src/time/Storage.hpp
Labels: enhancement

#1839 Fix roundoff problem if close to window boundary in `math::Bspline`
  src/math/Bspline.cpp
  src/math/tests/BSplineTest.cpp
  tests/serial/time/explicit/serial-coupling/DoNothingWithSmallSteps.cpp
  tests/serial/time/explicit/serial-coupling/DoNothingWithSmallSteps.xml
  tests/tests.cmake
Labels: bug, maintainability

#1796 Remove final export, fix initial export
  docs/changelog/1796.md
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantState.cpp
  src/precice/impl/ParticipantState.hpp
Labels: bug, breaking change

#1840 Add support for configurable wait in finalize
  docs/changelog/1840.md
  src/precice/config/Configuration.cpp
  src/precice/config/Configuration.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
  tests/serial/lifecycle/ConstructOnlyWait.cpp
  tests/serial/lifecycle/ConstructOnlyWait.xml
  tests/serial/lifecycle/FullWait.cpp
  tests/serial/lifecycle/FullWait.xml
  tests/tests.cmake
Labels: enhancement

#1854 Add compiler detection for IntelLLVM
  CMakeLists.txt
Labels: bug

#1788 Change valid-digits to min-timestep
  docs/changelog/1788.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/config/Configuration.cpp
  src/precice/config/Configuration.hpp
  tests/parallel/PrimaryRankSockets.xml
  tests/serial/multi-coupling/MultiCoupling.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantHighTolerance.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantHighTolerance.xml
  tests/tests.cmake
Labels: breaking change
