Repository precice/precice, pull requests merged in 2023-09, with the labels that each got.

#1789 Check time window sizes for `method="first-participant"`
  docs/changelog/1789.md
  src/cplscheme/SerialCouplingScheme.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipant.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantChangingDt.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantChangingDt.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantFixedWindows.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantFixedWindows.xml
  tests/tests.cmake
Labels: bug, usability

#1791 Always perform mapping when entering new window.
  docs/changelog/1791.md
  src/precice/impl/ParticipantImpl.cpp
  tests/serial/action-timings/ActionTimingsSerialExplicit.cpp
  tests/serial/action-timings/ActionTimingsSerialImplicit.cpp
Labels: maintainability

#1792 Require at least two samples for `Storage::move()`
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/time/Storage.cpp
Labels: maintainability

#1795 Refactoring: Make `Waveform` a wrapper of `Storage`
  src/cplscheme/CouplingData.cpp
  src/mesh/Data.cpp
  src/time/Storage.cpp
  src/time/Storage.hpp
  src/time/Waveform.cpp
  src/time/Waveform.hpp
Labels: maintainability

#1806 Samplize nearest neighbour mapping tests
  src/mapping/tests/NearestNeighborMappingTest.cpp
Labels: maintainability

#1810 Installs the precice-profiling script as a program
  CMakeLists.txt
Labels: bug

#1816 Use python interpreter from env
  tools/profiling/precice-profiling
Labels: bug

#1812 Fix Archlinux CI
  .github/workflows/build-and-test.yml
Labels: bug

#1746 Use absolute timestamps
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/action/tests/PythonActionTest.cpp
  src/action/tests/ScaleActionTest.cpp
  src/action/tests/SummationActionTest.cpp
  src/com/SerializedStamples.cpp
  src/com/SerializedStamples.hpp
  src/com/tests/SerializedStamplesTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/math/bspline.cpp
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/precice/impl/DataContext.cpp
  src/precice/impl/MappingContext.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ReadDataContext.cpp
  src/precice/impl/ReadDataContext.hpp
  src/time/Storage.cpp
  src/time/Storage.hpp
  src/time/Waveform.cpp
  src/time/Waveform.hpp
  src/time/tests/StorageTest.cpp
  src/time/tests/WaveformTest.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipant.cpp
Labels: maintainability

#1765 Speed up bspline interpolation
  docs/changelog/1765.md
  src/math/Bspline.cpp
  src/math/Bspline.hpp
  src/math/bspline.cpp
  src/math/bspline.hpp
  src/math/tests/BSplineTest.cpp
  src/sources.cmake
  src/time/Storage.cpp
  src/time/Storage.hpp
  src/time/Waveform.cpp
Labels: enhancement
