Repository precice/precice, pull requests merged in 2023-08, with the labels that each got.

#1736 PUM mapping: use only a single cluster for small cases
  docs/changelog/1736.md
  src/mapping/impl/CreateClustering.hpp
  src/mapping/tests/PartitionOfUnityMappingTest.cpp
Labels: enhancement

#1760 Link developer tooling from CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#1630 Add Ginkgo and hipSOLVER GPU support for RBF mappings [continued]
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  cmake/CTestConfig.cmake
  docs/changelog/1630.md
  src/mapping/GinkgoRadialBasisFctSolver.hpp
  src/mapping/RadialBasisFctMapping.hpp
  src/mapping/RadialBasisFctSolver.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/device/CudaQRSolver.cu
  src/mapping/device/CudaQRSolver.cuh
  src/mapping/device/GinkgoRBFKernels.cpp
  src/mapping/device/HipQRSolver.hip.cpp
  src/mapping/device/HipQRSolver.hip.hpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/impl/SphericalVertexCluster.hpp
  src/mapping/tests/GinkgoRadialBasisFctSolverTest.cpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/mapping/tests/PartitionOfUnityMappingTest.cpp
  src/mapping/tests/RadialBasisFctHelper.hpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/mapping/tests/mapping-rbf-cuda-config.xml
  src/mapping/tests/mapping-rbf-hip-config.xml
  src/mapping/tests/mapping-rbf-iterative-config.xml
  src/mapping/tests/mapping-rbf-omp-config.xml
  src/mapping/tests/mapping-rbf-pum-direct-config.xml
  src/sources.cmake
  src/tests.cmake
  tools/building/updateSourceFiles.py
Labels: enhancement

#1761 Replace pandas with polars in precice-events
  docs/changelog/1761.md
  tools/profiling/precice-events
Labels: compatibility

#1756 Test precice-events analyse with venv
  tools/profiling/CMakeLists.txt
  tools/profiling/precice-events
  tools/profiling/tests/from-common-dir/.test
  tools/profiling/tests/from-solver-dirs/.test
  tools/profiling/tests/one-parallel-solver-different-ids/.test
  tools/profiling/tests/one-parallel-solver/.test
  tools/profiling/tests/one-parallel-solver/events.csv
  tools/profiling/tests/one-serial-damaged/.test
  tools/profiling/tests/one-serial-solver/.test
  tools/profiling/tests/one-solver-multiple-runs/.test
  tools/profiling/tests/simple-test.cmake
  tools/profiling/tests/two-mixed-solvers/.test
  tools/profiling/tests/two-parallel-solvers/.test
  tools/profiling/tests/two-serial-solvers/.test
Labels: maintainability

#1744 Name CMake variables consistently
  .github/workflows/build-and-test-mac.yml
  .github/workflows/build-and-test.yml
  .github/workflows/release.yml
  CMakeLists.txt
  cmake/GenerateVersionInformation.cmake
  cmake/Validation.cmake
  docs/changelog/1744.md
  extras/bindings/fortran/src/preciceFortran.cpp
Labels: breaking change

#1771 Refactoring: Put B-Spline interpolation separate file
  src/math/bspline.cpp
  src/math/bspline.hpp
  src/math/tests/BSplineTest.cpp
  src/sources.cmake
  src/tests.cmake
  src/time/Waveform.cpp
Labels: maintainability

#1773 Fix profiling tests checking for pandas instead of polars
  tools/profiling/CMakeLists.txt
  tools/profiling/precice-events
  tools/profiling/tests/simple-test.cmake
Labels: bug

#1781 Removing mpi-single and mpi-singleports tags
  src/com/config/CommunicationConfiguration.cpp
  src/m2n/config/M2NConfiguration.cpp
  src/precice/config/ParticipantConfiguration.cpp
  tests/parallel/GlobalRBFPartitioning.xml
  tests/parallel/GlobalRBFPartitioningPETSc.xml
  tests/parallel/LocalRBFPartitioning.xml
  tests/parallel/LocalRBFPartitioningPETSc.xml
  tests/parallel/NearestProjectionRePartitioning.xml
  tests/parallel/TestFinalize.xml
  tests/parallel/UserDefinedMPICommunicator.xml
  tests/parallel/UserDefinedMPICommunicatorPetRBF.xml
  tests/parallel/distributed-communication/TestDistributedCommunicationGatherScatterMPI.xml
  tests/parallel/distributed-communication/TestDistributedCommunicationP2PMPI.xml
  tests/parallel/distributed-communication/TestDistributedCommunicationP2PSockets.xml
  tests/parallel/mapping-nearest-neighbor-gradient/GradientTestParallelVector.xml
  tests/quasi-newton/parallel/TestQN1.xml
  tests/quasi-newton/parallel/TestQN1EmptyPartition.xml
  tests/quasi-newton/parallel/TestQN2.xml
  tests/quasi-newton/parallel/TestQN2EmptyPartition.xml
  tests/quasi-newton/parallel/TestQN3.xml
  tests/quasi-newton/parallel/TestQN3EmptyPartition.xml
  tests/serial/mapping-nearest-neighbor-gradient/GradientTestBidirectionalReadScalar.xml
Labels: breaking change

#1769 Correct definition of convergence measure
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
Labels: documentation

#1779 Fix outdated error message in ParticipantImpl
  src/precice/impl/ParticipantImpl.cpp
Labels: documentation

#1775 Prevent unintended extrapolation in B-splines
  src/math/bspline.cpp
Labels: bug, maintainability

#1784 Removing exporters (legacy vtk in parallel)
  docs/changelog/1784.md
  src/precice/config/ParticipantConfiguration.cpp
  tests/parallel/ExportTimeseries.xml
  tests/parallel/NearestProjectionRePartitioning.xml
Labels: breaking change
