Repository precice/precice, pull requests merged in 2023-11, with the labels that each got.

#1847 Fix deadlock in two-level initialization
  docs/changelog/1847.md
  src/partition/ReceivedPartition.cpp
  tests/parallel/TestBoundingBoxInitializationEmpty.cpp
  tests/parallel/TestBoundingBoxInitializationEmpty.xml
  tests/tests.cmake
Labels: bug

#1869 Improve error message in PUM
  src/mapping/PartitionOfUnityMapping.hpp
Labels: usability

#1705 Fix subcycling and mix time-window-sizes in `CompositionalCouplingScheme`
  docs/changelog/1705.md
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/acceleration/test/helper.hpp
  src/com/tests/SerializedStamplesTest.cpp
  src/com/tests/helper.hpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
  src/precice/impl/WriteDataContext.cpp
  src/precice/impl/WriteDataContext.hpp
  src/tests.cmake
  src/time/Storage.cpp
  src/time/Storage.hpp
  tests/serial/mixed-time-window-sizes/explicit/ParallelParallel.cpp
  tests/serial/mixed-time-window-sizes/explicit/ParallelParallel.xml
  tests/serial/mixed-time-window-sizes/explicit/ParallelSerial.cpp
  tests/serial/mixed-time-window-sizes/explicit/ParallelSerial.xml
  tests/serial/mixed-time-window-sizes/explicit/SerialParallel.cpp
  tests/serial/mixed-time-window-sizes/explicit/SerialParallel.xml
  tests/serial/mixed-time-window-sizes/explicit/SerialSerial.cpp
  tests/serial/mixed-time-window-sizes/explicit/SerialSerial.xml
  tests/serial/mixed-time-window-sizes/helper.cpp
  tests/serial/mixed-time-window-sizes/helper.hpp
  tests/serial/mixed-time-window-sizes/implicit/ParallelParallel.cpp
  tests/serial/mixed-time-window-sizes/implicit/ParallelParallel.xml
  tests/serial/mixed-time-window-sizes/implicit/ParallelSerial.cpp
  tests/serial/mixed-time-window-sizes/implicit/ParallelSerial.xml
  tests/serial/mixed-time-window-sizes/implicit/SerialParallel.cpp
  tests/serial/mixed-time-window-sizes/implicit/SerialParallel.xml
  tests/serial/mixed-time-window-sizes/implicit/SerialSerial.cpp
  tests/serial/mixed-time-window-sizes/implicit/SerialSerial.xml
  tests/serial/three-solvers/ThreeSolversParallelExplicitImplicit.cpp
  tests/serial/three-solvers/ThreeSolversParallelExplicitImplicit.xml
  tests/serial/time/explicit/compositional/DoNothingWithSubcycling.cpp
  tests/serial/time/explicit/compositional/DoNothingWithSubcycling.xml
  tests/serial/time/implicit/compositional/DoNothingWithSubcycling.cpp
  tests/serial/time/implicit/compositional/DoNothingWithSubcycling.xml
  tests/serial/time/implicit/compositional/ReadWriteScalarDataWithSubcycling.cpp
  tests/serial/time/implicit/compositional/ReadWriteScalarDataWithSubcycling.xml
  tests/tests.cmake
Labels: bug

#1877 Fix exporting iterations
  src/precice/impl/ParticipantImpl.cpp
Labels: bug

#1885 Fix zero write data bug
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/WriteDataContext.cpp
  src/precice/impl/WriteDataContext.hpp
Labels: bug

#1886 Fix type mismatch in Config Parser
  src/xml/ConfigParser.cpp
Labels: bug, compatibility

#1547 Simplify FindPETSc to directly use pkgconfig target
  cmake/modules/FindPETSc.cmake
  docs/changelog/1547.md
Labels: maintainability, breaking change, petsc

#1887 More explicit time management in BaseCouplingScheme
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
Labels: maintainability

#1379 Extend Aitken acceleration to handle multiple data sets
  docs/changelog/1379.md
  src/acceleration/Acceleration.cpp
  src/acceleration/Acceleration.hpp
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/AitkenAcceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
Labels: bug

#1882 Remove `min-time-step-size`
  docs/changelog/1882.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/BiCouplingScheme.cpp
  src/cplscheme/BiCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/config/Configuration.cpp
  src/precice/config/Configuration.hpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantHighTolerance.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataFirstParticipantHighTolerance.xml
  tests/tests.cmake
Labels: maintainability

#1893 Update badges and URLs in README.md
  docs/README.md
Labels: documentation

#1863 Give warning info other than error by zero-update of `V` in QN-update
  docs/changelog/1863.md
  src/acceleration/BaseQNAcceleration.cpp
  tests/quasi-newton/parallel/TestQN10.cpp
  tests/quasi-newton/parallel/TestQN10.xml
  tests/quasi-newton/parallel/TestQN10EmptyPartition.cpp
  tests/quasi-newton/parallel/TestQN10EmptyPartition.xml
  tests/quasi-newton/serial/TestQN10.cpp
  tests/quasi-newton/serial/TestQN10.xml
  tests/tests.cmake
Labels: bug, hotfix

#1892 Fix const relax acceleration
  src/acceleration/Acceleration.cpp
  src/acceleration/Acceleration.hpp
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/AitkenAcceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/ConstantRelaxationAcceleration.cpp
  src/acceleration/ConstantRelaxationAcceleration.hpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.hpp
  src/time/Storage.cpp
  src/time/Storage.hpp
Labels: bug

#1871 Add Wendland C8 RBF
  docs/changelog/1871.md
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/config/MappingConfigurationTypes.hpp
  src/mapping/device/GinkgoRBFKernels.cpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/tests/GinkgoRadialBasisFctSolverTest.cpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/mapping/tests/mapping-rbf-direct-config.xml
  src/mapping/tests/mapping-rbf-iterative-config.xml
  src/mapping/tests/mapping-rbf-pum-direct-config.xml
Labels: enhancement

#1901 Fix EventRegistry stopping backend without starting it.
  src/profiling/EventUtils.cpp
  src/profiling/EventUtils.hpp
Labels: bug

#1897 Replace `_computedTimeWindowPart` with `_time`
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/SerialCouplingScheme.cpp
  src/precice/impl/ParticipantImpl.cpp
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithWaveformSubcyclingDifferentDts.cpp
Labels: maintainability

#1895 Add a warning for empty IQN matrix, but keep going
  docs/changelog/1895.md
  src/acceleration/IQNILSAcceleration.cpp
Labels: bug, hotfix

#1900 Add test for Aitken with preconditioner
  src/acceleration/Acceleration.cpp
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/impl/Preconditioner.hpp
  src/acceleration/test/AccelerationSerialTest.cpp
Labels: maintainability

#1867 Add warning for very small time step sizes
  docs/changelog/1867.md
  src/precice/impl/ParticipantImpl.cpp
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling6400Steps.cpp
Labels: usability

#1815 Correct the threshold value in truncation of SVD
  .cache/clangd/index/AccessReceivedMeshOverlapNoWriteTwoLevelInit.cpp.3F2F0938955939B8.idx
  docs/changelog/1815.md
  src/acceleration/impl/SVDFactorization.hpp
  src/acceleration/test/SVDFactorizationTest.cpp
  src/tests.cmake
Labels: bug

#1906 Make API more restrictive w.r.t correct context for calling `readData` and `writeData`
  docs/changelog/1906.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/precice/impl/ParticipantImpl.cpp
  tests/parallel/ExportTimeseries.cpp
  tests/parallel/mapping-volume/ParallelCube3To1.cpp
  tests/serial/mapping-volume/helpers.cpp
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithWaveformSubcyclingDifferentDts.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSamplingFirstNoInit.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingFirst.cpp
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSamplingFirstNoInit.cpp
Labels: usability, maintainability
