Repository precice/precice, pull requests merged in 2024-01, with the labels that each got.

#1916 Tidy the API documentation
  docs/documents/000_main.dox
  docs/documents/span.dox
  extras/bindings/c/include/precice/preciceC.h
  extras/bindings/fortran/include/precice/preciceFortran.hpp
  extras/bindings/fortran/src/preciceFortran.cpp
  src/precice/Participant.cpp
  src/precice/Participant.hpp
  src/precice/Types.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
Labels: documentation

#1675 Geometric multiscale feature
  docs/changelog/1439.md
  src/mapping/AxialGeoMultiscaleMapping.cpp
  src/mapping/AxialGeoMultiscaleMapping.hpp
  src/mapping/RadialGeoMultiscaleMapping.cpp
  src/mapping/RadialGeoMultiscaleMapping.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/config/MappingConfiguration.hpp
  src/mapping/tests/AxialGeoMultiscaleMappingTest.cpp
  src/mapping/tests/RadialGeoMultiscaleMappingTest.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/sources.cmake
  src/tests.cmake
  tests/geometric-multiscale/AxialGeoMultiscale.cpp
  tests/geometric-multiscale/AxialGeoMultiscale.xml
  tests/geometric-multiscale/RadialGeoMultiscale.cpp
  tests/geometric-multiscale/RadialGeoMultiscale.xml
  tests/tests.cmake
Labels: enhancement

#1931 Fix missing bindings include in build pc file
  CMakeLists.txt
  cmake/binary.pc.in
  docs/changelog/1931.md
Labels: bug, hotfix

#1935 Fix max-time reaching end of time window
  src/cplscheme/BaseCouplingScheme.cpp
  src/precice/impl/ParticipantImpl.cpp
  tests/serial/time/explicit/parallel-coupling/DoNonfittingWindows.cpp
Labels: bug

#1940 Hotfix v2.5.1
  CHANGELOG.md
  CMakeLists.txt
  cmake/binary.pc.in
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/IQNILSAcceleration.cpp
  src/xml/ConfigParser.cpp
Labels: hotfix

#1941 Add check for polars version
  tools/profiling/precice-profiling
Labels: usability
