Repository precice/precice, pull requests merged in 2024-12, with the labels that each got.

#2151 Fix exporter crash on non-existant data
  src/io/ExportCSV.cpp
  src/io/ExportXML.cpp
  src/io/tests/ExportCSVTest.cpp
  src/io/tests/ExportVTKTest.cpp
  src/io/tests/ExportVTPTest.cpp
  src/io/tests/ExportVTUTest.cpp
  src/testing/Testing.cpp
  src/testing/Testing.hpp
Labels: bug

#2155 Release preCICE using annotated tags
  tools/releasing/PULL_REQUEST_TEMPLATE/release_pull_request_template.md
Labels: documentation

#2157 Cleanup logging includes
  src/logging/LogConfiguration.cpp
  src/logging/LogConfiguration.hpp
  src/logging/Logger.cpp
  src/logging/Tracer.cpp
  src/logging/Tracer.hpp
  src/logging/config/LogConfiguration.cpp
  src/logging/config/LogConfiguration.hpp
  src/precice/config/Configuration.hpp
Labels: maintainability

#2079 Replace Ginkgo triangular solver by dense BLAS trsv
  CMakeLists.txt
  cmake/CTestConfig.cmake
  docs/changelog/2079.md
  src/mapping/GinkgoRadialBasisFctSolver.hpp
  src/mapping/device/CudaQRSolver.cu
  src/mapping/device/CudaQRSolver.cuh
  src/mapping/device/HipQRSolver.hip.cpp
  src/mapping/device/HipQRSolver.hip.hpp
Labels: enhancement

#2158 Compatibility with boost asio 1.86
  docs/changelog/2158.md
  src/com/SocketCommunication.cpp
  src/com/SocketCommunication.hpp
  src/com/SocketSendQueue.cpp
  src/com/SocketSendQueue.hpp
Labels: compatibility
