Repository precice/precice, pull requests merged in 2024-10, with the labels that each got.

#2087 Use . as default for CWD in m2n
  src/m2n/config/M2NConfiguration.cpp
Labels: documentation, configuration

#2086 Fix boolean default values in config reference
  src/xml/Printer.cpp
Labels: documentation, configuration

#2059 Implement RBF LOOCV error estimate
  src/mapping/MathHelper.hpp
  src/mapping/RadialBasisFctSolver.hpp
  src/mapping/tests/RadialBasisFctMappingTest.cpp
  src/sources.cmake
Labels: usability

#2095 Keep order of attributes in markdown docs
  src/xml/Printer.cpp
  src/xml/XMLTag.cpp
  src/xml/XMLTag.hpp
Labels: documentation

#2096 Cleanup XML attribute handling and fix order
  src/io/tests/ExportConfigurationTest.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/xml/Printer.cpp
  src/xml/ValueParser.cpp
  src/xml/XMLTag.cpp
  src/xml/XMLTag.hpp
  src/xml/tests/ParserTest.cpp
  src/xml/tests/XMLTest.cpp
  src/xml/tests/xmlparser_test.xml
Labels: documentation

#2090 Reword receive-mesh docs
  src/precice/config/ParticipantConfiguration.cpp
Labels: documentation

#2098 Cleanup convergence measure config
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
Labels: maintainability

#2107 Simplify Acceleration class by removing unnecessary functions
  src/acceleration/Acceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/cplscheme/BaseCouplingScheme.cpp
Labels: maintainability

#2108 Move initialization of vector and preconditioner into their own function
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/IQNILSAcceleration.hpp
  src/acceleration/IQNIMVJAcceleration.cpp
  src/acceleration/IQNIMVJAcceleration.hpp
Labels: maintainability

#2066 Handle event scoping in post
  docs/changelog/2066.md
  src/precice/impl/ParticipantImpl.cpp
  src/profiling/Event.cpp
  src/profiling/Event.hpp
  src/profiling/EventUtils.cpp
  src/profiling/EventUtils.hpp
  tools/profiling/precice-profiling
  tools/profiling/tests/from-common-dir/precice-profiling/A-0-1.json
  tools/profiling/tests/from-common-dir/precice-profiling/B-0-1.json
  tools/profiling/tests/from-solver-dirs/A/precice-profiling/A-0-1.json
  tools/profiling/tests/from-solver-dirs/B/precice-profiling/B-0-1.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-0-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-1-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-2-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-3-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-4-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-5-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-6-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-7-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-8-10.json
  tools/profiling/tests/one-parallel-solver-different-ids/B-9-10.json
  tools/profiling/tests/one-parallel-solver/B-0-10.json
  tools/profiling/tests/one-parallel-solver/B-1-10.json
  tools/profiling/tests/one-parallel-solver/B-2-10.json
  tools/profiling/tests/one-parallel-solver/B-3-10.json
  tools/profiling/tests/one-parallel-solver/B-4-10.json
  tools/profiling/tests/one-parallel-solver/B-5-10.json
  tools/profiling/tests/one-parallel-solver/B-6-10.json
  tools/profiling/tests/one-parallel-solver/B-7-10.json
  tools/profiling/tests/one-parallel-solver/B-8-10.json
  tools/profiling/tests/one-parallel-solver/B-9-10.json
  tools/profiling/tests/one-serial-damaged/A-0-1.json
  tools/profiling/tests/one-serial-solver/A-0-1.json
  tools/profiling/tests/one-serial-solver/B-0-1.json
  tools/profiling/tests/one-solver-multiple-runs/B-0-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-0-2.json
  tools/profiling/tests/one-solver-multiple-runs/B-0-4.json
  tools/profiling/tests/one-solver-multiple-runs/B-1-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-1-2.json
  tools/profiling/tests/one-solver-multiple-runs/B-1-4.json
  tools/profiling/tests/one-solver-multiple-runs/B-2-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-2-4.json
  tools/profiling/tests/one-solver-multiple-runs/B-3-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-3-4.json
  tools/profiling/tests/one-solver-multiple-runs/B-4-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-5-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-6-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-7-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-8-10.json
  tools/profiling/tests/one-solver-multiple-runs/B-9-10.json
  tools/profiling/tests/two-mixed-solvers/A-0-1.json
  tools/profiling/tests/two-mixed-solvers/B-0-2.json
  tools/profiling/tests/two-mixed-solvers/B-1-2.json
  tools/profiling/tests/two-parallel-solvers/A-0-2.json
  tools/profiling/tests/two-parallel-solvers/A-1-2.json
  tools/profiling/tests/two-parallel-solvers/B-0-2.json
  tools/profiling/tests/two-parallel-solvers/B-1-2.json
  tools/profiling/tests/two-serial-solvers/A-0-1.json
  tools/profiling/tests/two-serial-solvers/B-0-1.json
Labels: maintainability

#2117 Print nested events with indentation
  docs/changelog/2117.md
  tools/profiling/precice-profiling
Labels: usability
