Repository precice/precice, pull requests merged in 2024-04, with the labels that each got.

#1999 Fix skipping initial mappings in parallel
  docs/changelog/1999.md
  src/precice/impl/DataContext.cpp
  tests/parallel/map-initial-data/NonZeroData.cpp
  tests/parallel/map-initial-data/NonZeroData.xml
  tests/parallel/map-initial-data/ZeroData.cpp
  tests/parallel/map-initial-data/ZeroData.xml
  tests/parallel/map-initial-data/helper.hpp
  tests/tests.cmake
Labels: bug

#2000 Release v3.1.1
  CHANGELOG.md
  CMakeLists.txt
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/m2n/config/M2NConfiguration.cpp
  src/m2n/config/M2NConfiguration.hpp
  src/precice/config/Configuration.cpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/config/ParticipantConfiguration.hpp
  src/precice/impl/DataContext.cpp
  src/precice/impl/ParticipantImpl.cpp
  tests/parallel/map-initial-data/NonZeroData.cpp
  tests/parallel/map-initial-data/NonZeroData.xml
  tests/parallel/map-initial-data/ZeroData.cpp
  tests/parallel/map-initial-data/ZeroData.xml
  tests/parallel/map-initial-data/helper.hpp
  tests/tests.cmake
  tools/releasing/packaging/debian/changelog
Labels: bug

#2001 refactoring and small corrections of the Quasi Newton Method
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/IQNIMVJAcceleration.cpp
  src/acceleration/impl/QRFactorization.hpp
Labels: documentation

#2007 Add simple version check
  docs/changelog/2007.md
  src/xml/ConfigParser.cpp
Labels: usability

#2009 Fix polars warning in profiling script
  tools/profiling/precice-profiling
Labels: compatibility
