Repository precice/precice, pull requests merged in 2024-11, with the labels that each got.

#2125 Revert swapped participant and mesh name in export filenames
  src/io/ExportCSV.cpp
  src/io/ExportVTK.cpp
  src/io/ExportXML.cpp
Labels: bug

#2112 Add default initial relaxation to Aitken
  docs/changelog/2112.md
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  tests/serial/aitken/DefaultInitialRelaxation.cpp
  tests/serial/aitken/DefaultInitialRelaxation.xml
  tests/serial/aitken/DefinedInitialRelaxation.cpp
  tests/serial/aitken/DefinedInitialRelaxation.xml
  tests/tests.cmake
Labels: usability, configuration

#2124 Add error for swapped meshes in mappings
  docs/changelog/2124.md
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/ParticipantState.cpp
Labels: usability, configuration

#2120 Add additional fundamental events
  src/cplscheme/BaseCouplingScheme.cpp
  src/m2n/M2N.cpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantState.cpp
  src/precice/impl/ParticipantState.hpp
Labels: usability

#2130 Add events to API calls
  docs/changelog/2130.md
  src/precice/impl/ParticipantImpl.cpp
Labels: enhancement

#2136 Set default restart method for IMVJ
  docs/changelog/2136.md
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
Labels: usability

#2139 Speedup print of test list
  src/testing/main.cpp
Labels: maintainability

#2140 Remove exchange-dir from remeshing tests
  tests/remeshing/ResetAfterSubcycling.xml
  tests/remeshing/ResetWhileIterating.xml
  tests/remeshing/SubcylingAfterReset.xml
  tests/remeshing/parallel-explicit/two-meshes/LocalMapping.xml
  tests/remeshing/parallel-explicit/two-meshes/RemoteMapping.xml
  tests/remeshing/parallel-implicit/acceleration/IQN-ILS/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/acceleration/IQN-ILS/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/acceleration/IQN-ILS/RemeshSecondSerial.xml
  tests/remeshing/parallel-implicit/acceleration/IQN-IMVJ/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/acceleration/IQN-IMVJ/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/acceleration/IQN-IMVJ/RemeshSecondSerial.xml
  tests/remeshing/parallel-implicit/acceleration/aitken/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/acceleration/aitken/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/acceleration/aitken/RemeshSecondSerial.xml
  tests/remeshing/parallel-implicit/acceleration/constant/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/acceleration/constant/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/acceleration/constant/RemeshSecondSerial.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshBoth.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshBoth2LI.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshFirst.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshFirst2LI.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshSecond.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshSecond2LI.xml
  tests/remeshing/parallel-implicit/changed-mapping/RemeshSecondSerial.xml
  tests/remeshing/parallel-implicit/changed-partition/OverlapBoth.xml
  tests/remeshing/parallel-implicit/changed-partition/OverlapBoth2LI.xml
  tests/remeshing/parallel-implicit/changed-partition/ScatterFirst.xml
  tests/remeshing/parallel-implicit/changed-partition/ScatterFirst2LI.xml
  tests/remeshing/parallel-implicit/changed-partition/ScatterSecond.xml
  tests/remeshing/parallel-implicit/changed-partition/ScatterSecond2LI.xml
  tests/remeshing/parallel-implicit/changed-partition/SwapFirst.xml
  tests/remeshing/parallel-implicit/changed-partition/SwapFirst2LI.xml
  tests/remeshing/parallel-implicit/changed-partition/SwapSecond.xml
  tests/remeshing/parallel-implicit/changed-partition/SwapSecond2LI.xml
  tests/remeshing/parallel-implicit/convergence/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/convergence/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/convergence/RemeshSecondSerial.xml
  tests/remeshing/parallel-implicit/noop/RemeshBoth.xml
  tests/remeshing/parallel-implicit/noop/RemeshBoth2LI.xml
  tests/remeshing/parallel-implicit/noop/RemeshBothSerial.xml
  tests/remeshing/parallel-implicit/noop/RemeshFirst.xml
  tests/remeshing/parallel-implicit/noop/RemeshFirst2LI.xml
  tests/remeshing/parallel-implicit/noop/RemeshFirstSerial.xml
  tests/remeshing/parallel-implicit/noop/RemeshSecond.xml
  tests/remeshing/parallel-implicit/noop/RemeshSecond2LI.xml
  tests/remeshing/parallel-implicit/noop/RemeshSecondSerial.xml
Labels: bug

#2143 Fix event name of _GLOBAL missing in integration tests
  src/profiling/EventUtils.cpp
Labels: bug

#2145 Fix list_units not showing data tests
  src/testing/main.cpp
Labels: bug

#2144 Fix initial data in multi-coupling schemes
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/MultiCouplingScheme.hpp
  tests/serial/multi-coupling/MultiCouplingThreeSolvers5.xml
Labels: bug, configuration

#2134 Add multi coupling initialize test
  tests/serial/multi-coupling/MultiCouplingThreeSolvers10.cpp
  tests/serial/multi-coupling/MultiCouplingThreeSolvers10.xml
  tests/serial/multi-coupling/MultiCouplingThreeSolvers7.cpp
  tests/serial/multi-coupling/MultiCouplingThreeSolvers7.xml
  tests/serial/multi-coupling/MultiCouplingThreeSolvers8.cpp
  tests/serial/multi-coupling/MultiCouplingThreeSolvers8.xml
  tests/serial/multi-coupling/MultiCouplingThreeSolvers9.cpp
  tests/serial/multi-coupling/MultiCouplingThreeSolvers9.xml
  tests/tests.cmake
Labels: bug

#2005 Extend QN acceleration to waveform iterations
  docs/changelog/2005.md
  src/acceleration/Acceleration.hpp
  src/acceleration/AitkenAcceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/ConstantRelaxationAcceleration.hpp
  src/acceleration/IQNILSAcceleration.cpp
  src/acceleration/IQNILSAcceleration.hpp
  src/acceleration/IQNIMVJAcceleration.cpp
  src/acceleration/IQNIMVJAcceleration.hpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/sources.cmake
  src/tests.cmake
  src/time/TimeGrids.cpp
  src/time/TimeGrids.hpp
  src/time/tests/TimeGridsTest.cpp
  tests/quasi-newton/helpers.cpp
  tests/quasi-newton/helpers.hpp
  tests/quasi-newton/parallel/TestQN11.cpp
  tests/quasi-newton/parallel/TestQN11.xml
  tests/quasi-newton/serial/TestQN11.cpp
  tests/quasi-newton/serial/TestQN11.xml
  tests/quasi-newton/serial/TestQN12.cpp
  tests/quasi-newton/serial/TestQN12.xml
  tests/quasi-newton/serial/TestQN13.cpp
  tests/quasi-newton/serial/TestQN13.xml
  tests/quasi-newton/serial/TestQN14.cpp
  tests/quasi-newton/serial/TestQN14.xml
  tests/tests.cmake
Labels: enhancement

#2141 Fix crash in destructor after exception in communication initialization
  docs/changelog/2141.md
  src/precice/impl/ParticipantImpl.cpp
Labels: bug

#2148 Refactor test setup into separate class
  src/testing/TestContext.cpp
  src/testing/TestContext.hpp
  src/testing/Testing.hpp
Labels: maintainability
