Repository precice/precice, pull requests merged in 2024-06, with the labels that each got.

#2032 Add mesh name to convergence file header
  docs/changelog/2032.md
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
Labels: usability

#2023 Release v3.1.2
  CHANGELOG.md
  CMakeLists.txt
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  tests/serial/compositional/OneActivatedMuscle.cpp
  tests/serial/compositional/OneActivatedMuscle.xml
  tests/serial/compositional/TwoActivatedMuscles.cpp
  tests/serial/compositional/TwoActivatedMuscles.xml
  tests/serial/compositional/data/README.md
  tests/serial/compositional/data/implicit-first/AllParallel.cpp
  tests/serial/compositional/data/implicit-first/AllParallel.xml
  tests/serial/compositional/data/implicit-first/Parallel.cpp
  tests/serial/compositional/data/implicit-first/Parallel.xml
  tests/serial/compositional/data/implicit-first/SerialFirst.cpp
  tests/serial/compositional/data/implicit-first/SerialFirst.xml
  tests/serial/compositional/data/implicit-first/SerialSecond.cpp
  tests/serial/compositional/data/implicit-first/SerialSecond.xml
  tests/serial/compositional/data/implicit-second/AllParallel.cpp
  tests/serial/compositional/data/implicit-second/AllParallel.xml
  tests/serial/compositional/data/implicit-second/Parallel.cpp
  tests/serial/compositional/data/implicit-second/Parallel.xml
  tests/serial/compositional/data/implicit-second/SerialFirst.cpp
  tests/serial/compositional/data/implicit-second/SerialFirst.xml
  tests/serial/compositional/data/implicit-second/SerialSecond.cpp
  tests/serial/compositional/data/implicit-second/SerialSecond.xml
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/ParallelImplicit.cpp
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/SerialImplicit.cpp
  tests/serial/map-if-necessary/three-solvers/with-substeps/ParallelImplicit.cpp
  tests/serial/map-if-necessary/three-solvers/with-substeps/SerialImplicit.cpp
  tests/serial/map-if-necessary/three-solvers/without-substeps/ParallelImplicit.cpp
  tests/serial/map-if-necessary/three-solvers/without-substeps/SerialImplicit.cpp
  tests/tests.cmake
  tools/releasing/packaging/debian/changelog
Labels: bug, hotfix

#2036 Remove custom time at CouplingScheme initalization
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/cplscheme/CompositionalCouplingScheme.hpp
  src/cplscheme/CouplingScheme.hpp
  src/cplscheme/tests/CompositionalCouplingSchemeTest.cpp
  src/cplscheme/tests/DummyCouplingScheme.cpp
  src/cplscheme/tests/DummyCouplingScheme.hpp
  src/cplscheme/tests/ExplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/ParallelImplicitCouplingSchemeTest.cpp
  src/cplscheme/tests/SerialImplicitCouplingSchemeTest.cpp
  src/precice/impl/ParticipantImpl.cpp
Labels: maintainability

#2040 Skip export handling if no exports are defined
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantState.cpp
  src/precice/impl/ParticipantState.hpp
Labels: maintainability

#2041 Add handleExports event
  docs/changelog/2041.md
  src/precice/impl/ParticipantImpl.cpp
Labels: maintainability

#2042 Cleanup exports in Participant
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
Labels: maintainability

#2039 Remove `MAX_WAVEFORM_DEGREE`
  docs/changelog/2039.md
  src/mesh/config/DataConfiguration.cpp
  src/time/Storage.cpp
  src/time/Time.cpp
  src/time/Time.hpp
Labels: enhancement
