Repository precice/precice, pull requests merged in 2024-07, with the labels that each got.

#2047 Extend error mesage on undefined data
  src/precice/impl/ValidationMacros.hpp
Labels: usability

#2046 Fix error messages for reading/writing data on undefined mesh
  src/precice/config/ParticipantConfiguration.cpp
Labels: bug

#2050 Add precice user to docker releases
  tools/releasing/packaging/docker/README.md
  tools/releasing/packaging/docker/nightly.dockerfile
  tools/releasing/packaging/docker/release.dockerfile
Labels: usability

#2044 Add error for missing samples when initializing coupling schemes
  docs/changelog/2044.md
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
Labels: bug, configuration

#2053 Refactor mesh information into exporters
  src/io/Export.hpp
  src/io/ExportCSV.cpp
  src/io/ExportCSV.hpp
  src/io/ExportContext.hpp
  src/io/ExportVTK.cpp
  src/io/ExportVTK.hpp
  src/io/ExportVTP.cpp
  src/io/ExportVTP.hpp
  src/io/ExportVTU.cpp
  src/io/ExportVTU.hpp
  src/io/ExportXML.cpp
  src/io/ExportXML.hpp
  src/io/tests/ExportCSVTest.cpp
  src/io/tests/ExportVTKTest.cpp
  src/io/tests/ExportVTPTest.cpp
  src/io/tests/ExportVTUTest.cpp
  src/mapping/PartitionOfUnityMapping.hpp
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/precice/config/ParticipantConfiguration.cpp
  src/precice/impl/ParticipantState.cpp
Labels: maintainability

#2056 Use BoostConfig.cmake to find boost with CMake
  CMakeLists.txt
  docs/changelog/2056.md
Labels: building, dependencies

#2055 Add series to exporter
  docs/changelog/2055.md
  src/io/Export.cpp
  src/io/Export.hpp
  src/io/ExportCSV.cpp
  src/io/ExportCSV.hpp
  src/io/ExportVTK.cpp
  src/io/ExportVTK.hpp
  src/io/ExportXML.cpp
  src/io/ExportXML.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantState.cpp
  src/precice/impl/ParticipantState.hpp
  src/sources.cmake
Labels: enhancement

#2062 Fix tag help on typo
  src/xml/ConfigParser.cpp
Labels: bug

#2051 Replace Ginkgo kernel launch by Kokkos extension
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  docs/changelog/2051.md
  src/cplscheme/CompositionalCouplingScheme.cpp
  src/mapping/GinkgoDefinitions.hpp
  src/mapping/GinkgoRadialBasisFctSolver.hpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/device/CudaQRSolver.cu
  src/mapping/device/CudaQRSolver.cuh
  src/mapping/device/Ginkgo.cpp
  src/mapping/device/Ginkgo.hpp
  src/mapping/device/GinkgoRBFKernels.cpp
  src/mapping/device/GinkgoRBFKernels.hpp
  src/mapping/device/HipQRSolver.hip.cpp
  src/mapping/device/HipQRSolver.hip.hpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/tests/GinkgoRadialBasisFctSolverTest.cpp
  src/mapping/tests/MappingConfigurationTest.cpp
  src/precice/impl/ParticipantImpl.cpp
  src/sources.cmake
  src/testing/TestContext.cpp
  src/testing/TestContext.hpp
  src/testing/main.cpp
Labels: compatibility, dependencies
