Repository precice/precice, pull requests merged in 2025-01, with the labels that each got.

#1502 Add framework for benchmarks
  .github/workflows/build-and-test.yml
  CMakeLists.txt
  benchmarks/bb.cpp
  benchmarks/helper.hpp
  benchmarks/main.cpp
  benchmarks/mesh-index.cpp
  benchmarks/mesh-tagging.cpp
  benchmarks/rbf-assembly-kernels.cpp
  benchmarks/sources.cmake
  benchmarks/write-data.cpp
  benchmarks/write-data.xml
  src/testing/SourceLocation.hpp.in
  tools/building/updateSourceFiles.py
Labels: enhancement, maintainability

#2165 Force kebab style for XML Attributes and Namespaces
  src/utils/String.cpp
  src/utils/String.hpp
  src/xml/XMLAttribute.hpp
  src/xml/XMLTag.cpp
Labels: maintainability

#2163 Add test for subcycling in Aitken accleration
  docs/changelog/2163.md
  src/acceleration/AitkenAcceleration.cpp
  tests/serial/aitken/WithSubsteps.cpp
  tests/serial/aitken/WithSubsteps.xml
  tests/tests.cmake
Labels: enhancement

#2168 Simplify compilation of Basisfunctions for devices
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/impl/BasisFunctions.hpp
Labels: building

#2170 Add working directory to preCICE hello
  docs/changelog/2170.md
  src/precice/impl/ParticipantImpl.cpp
Labels: usability

#2184 Add NP projection information
  docs/changelog/2184.md
  src/mapping/NearestProjectionMapping.cpp
  src/mapping/Polation.cpp
  src/mapping/Polation.hpp
Labels: usability
