Repository precice/precice, pull requests merged in 2025-05, with the labels that each got.

#2295 Fix parameter descriptions in `preciceC.h`
  extras/bindings/c/include/precice/preciceC.h
Labels: documentation

#2298 Fix file detection of precice-profiling merge
  docs/changelog/2298.md
  tools/profiling/precice-profiling
Labels: bug, usability

#2300 Hardcode preCICE as shared library
  CMakeLists.txt
  CMakePresets.json
  cmake/PrintHelper.cmake
  docs/changelog/2300.md
  tools/releasing/packaging/Arch_User_Repository/PKGBUILD
Labels: building, trigger-system-tests

#2306 Use SAX2 header instead of SAX
  cmake/Validation.cmake
  docs/changelog/2306.md
  src/xml/ConfigParser.cpp
Labels: bug, hotfix
