Repository precice/precice, pull requests merged in 2025-03, with the labels that each got.

#2169 Fix ginkgo mapping executor selection
  docs/changelog/2169.md
  src/mapping/GinkgoRadialBasisFctSolver.hpp
  src/mapping/device/GinkgoRBFKernels.cpp
  src/mapping/device/GinkgoRBFKernels.hpp
Labels: bug

#2188 Use correct time in watch integral calculation and watch points
  docs/changelog/2188.md
  src/precice/impl/WatchIntegral.cpp
  src/precice/impl/WatchIntegral.hpp
  src/precice/impl/WatchPoint.cpp
  src/precice/impl/WatchPoint.hpp
  src/precice/tests/WatchIntegralTest.cpp
  src/precice/tests/WatchPointTest.cpp
  tests/serial/watch/WatchIntegralScaleAndNoScaleParallel.cpp
  tests/serial/watch/WatchIntegralScaleAndNoScaleParallel.xml
  tests/serial/watch/WatchIntegralScaleAndNoScaleSerial.cpp
  tests/serial/watch/WatchIntegralScaleAndNoScaleSerial.xml
  tests/serial/watch/WatchPointParallel.cpp
  tests/serial/watch/WatchPointParallel.xml
  tests/serial/watch/WatchPointSerial.cpp
  tests/serial/watch/WatchPointSerial.xml
  tests/serial/watch/helpers.cpp
  tests/serial/watch/helpers.hpp
  tests/tests.cmake
Labels: bug

#2223 Fix size of initial gradients in zero read `CouplingData` and `_writeDataBuffer`
  docs/changelog/2223.md
  src/cplscheme/CouplingData.cpp
  src/precice/impl/WriteDataContext.cpp
Labels: bug, trigger-system-tests

#2221 Bugfix for test `DoNothingWithSmallSteps` with `substeps="true"`
  tests/serial/time/explicit/parallel-coupling/DoNothingWithSmallStepsNoSubsteps.cpp
  tests/serial/time/explicit/parallel-coupling/DoNothingWithSmallStepsNoSubsteps.xml
  tests/serial/time/explicit/parallel-coupling/DoNothingWithSmallStepsSubsteps.cpp
  tests/serial/time/explicit/parallel-coupling/DoNothingWithSmallStepsSubsteps.xml
  tests/serial/time/explicit/serial-coupling/DoNothingWithSmallStepsNoSubsteps.cpp
  tests/serial/time/explicit/serial-coupling/DoNothingWithSmallStepsNoSubsteps.xml
  tests/serial/time/explicit/serial-coupling/DoNothingWithSmallStepsSubsteps.cpp
  tests/serial/time/explicit/serial-coupling/DoNothingWithSmallStepsSubsteps.xml
  tests/serial/time/helpers.cpp
  tests/serial/time/helpers.hpp
  tests/serial/time/implicit/parallel-coupling/DoNothingWithSmallStepsNoSubsteps.cpp
  tests/serial/time/implicit/parallel-coupling/DoNothingWithSmallStepsNoSubsteps.xml
  tests/serial/time/implicit/parallel-coupling/DoNothingWithSmallStepsSubsteps.cpp
  tests/serial/time/implicit/parallel-coupling/DoNothingWithSmallStepsSubsteps.xml
  tests/serial/time/implicit/serial-coupling/DoNothingWithSmallStepsNoSubsteps.cpp
  tests/serial/time/implicit/serial-coupling/DoNothingWithSmallStepsNoSubsteps.xml
  tests/serial/time/implicit/serial-coupling/DoNothingWithSmallStepsSubsteps.cpp
  tests/serial/time/implicit/serial-coupling/DoNothingWithSmallStepsSubsteps.xml
  tests/tests.cmake
Labels: bug

#2224 Fix direct access for serial and filtered runs
  docs/changelog/2224.md
  src/partition/ReceivedPartition.cpp
  tests/serial/direct-mesh-access/DirectAccessFiltered.cpp
  tests/serial/direct-mesh-access/DirectAccessFiltered.xml
  tests/tests.cmake
Labels: bug

#2228 Simplify write buffer resize
  src/precice/impl/WriteDataContext.cpp
Labels: maintainability

#2154 Add relative times to profiling analyse
  tools/profiling/precice-profiling
Labels: enhancement

#2127 Expand data in profiling export
  tools/profiling/precice-profiling
Labels: enhancement

#2235 Handle substeps with remeshing
  src/mesh/Mesh.cpp
  src/mesh/Mesh.hpp
  src/precice/impl/ParticipantImpl.cpp
  src/precice/impl/ParticipantImpl.hpp
Labels: bug

#2236 Prevent write data with api access and remeshing
  src/precice/config/ParticipantConfiguration.cpp
Labels: usability

#2238 Enable exports in tests
  CMakeLists.txt
Labels: building

#2239 Fix a dangling reference in python actions
  src/action/PythonAction.cpp
  src/action/tests/PythonActionTest.cpp
Labels: bug

#1493 Pre-scaling weight monitoring with new QR filter
  docs/changelog/1493.md
  src/acceleration/Acceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/config/AccelerationConfiguration.cpp
  src/acceleration/config/AccelerationConfiguration.hpp
  src/acceleration/impl/QRFactorization.cpp
  src/acceleration/impl/QRFactorization.hpp
  src/acceleration/impl/ResidualSumPreconditioner.cpp
  src/acceleration/impl/ResidualSumPreconditioner.hpp
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/PreconditionerTest.cpp
  src/acceleration/test/QRFactorizationTest.cpp
  tests/quasi-newton/serial/TestQN15.cpp
  tests/quasi-newton/serial/TestQN15.xml
  tests/tests.cmake
Labels: enhancement

#2220 Update default to `substeps="true"`
  docs/changelog/2220.md
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  tests/quasi-newton/parallel/TestQN11.xml
  tests/quasi-newton/serial/TestQN11.xml
  tests/quasi-newton/serial/TestQN12.xml
  tests/quasi-newton/serial/TestQN13.xml
  tests/quasi-newton/serial/TestQN14.xml
  tests/serial/aitken/WithSubsteps.xml
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/ParallelExplicit.xml
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/ParallelImplicit.xml
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/SerialExplicit.xml
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/SerialImplicit.xml
  tests/serial/parallel-coupling/SolverAFirstSubsteps.xml
  tests/serial/parallel-coupling/SolverBFirstSubsteps.xml
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcycling.xml
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/explicit/parallel-coupling/DoManySmallSteps.xml
  tests/serial/time/explicit/parallel-coupling/DoNonfittingWindows.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling6400Steps.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling640Steps.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling64Steps.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcycling.xml
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/multi-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.xml
  tests/serial/time/implicit/parallel-coupling/ReadWriteScalarDataWithWaveformSubcyclingThird.xml
  tests/serial/time/implicit/parallel-coupling/WaveformSubcyclingWithDifferentNumberOfDts.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithSubcyclingNoSubsteps.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingMixed.xml
  tests/serial/time/implicit/serial-coupling/ReadWriteScalarDataWithWaveformSubcyclingThird.xml
Labels: enhancement, trigger-system-tests

#2242 Fix type of param in `writeAndMapData` doc
  src/precice/Participant.hpp
Labels: documentation

#2241 Rename develop preset to development
  CMakePresets.json
  docs/changelog/2241.md
Labels: building

#2244 Update pre-commit versions
  .codespellrc
  .pre-commit-config.yaml
  CHANGELOG.md
  CMakeLists.txt
  cmake/Validation.cmake
  docs/changelog/2244.md
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/impl/QRFactorization.hpp
  src/acceleration/impl/SVDFactorization.hpp
  src/action/tests/TestAction.py
  src/com/Communication.hpp
  src/com/MPIDirectCommunication.hpp
  src/com/tests/GenericTestFunctions.hpp
  src/logging/Logger.cpp
  src/mapping/config/MappingConfiguration.cpp
  src/mapping/impl/BasisFunctions.hpp
  src/mapping/tests/NearestProjectionMappingTest.cpp
  src/mapping/tests/PartitionOfUnityMappingTest.cpp
  src/math/barycenter.cpp
  src/mesh/BoundingBox.hpp
  src/mesh/Mesh.cpp
  src/precice/Participant.hpp
  src/precice/impl/DataContext.cpp
  src/testing/TestContext.cpp
  src/testing/TestContext.hpp
  src/utils/Parallel.hpp
  src/utils/algorithm.hpp
Labels: maintainability

#2245 Add script to check symbols
  tools/building/README.md
  tools/building/checkSymbols
Labels: maintainability

#2246 Add resetMesh to bindings
  extras/bindings/c/include/precice/preciceC.h
  extras/bindings/c/src/preciceC.cpp
  extras/bindings/fortran/include/precice/preciceFortran.hpp
  extras/bindings/fortran/src/preciceFortran.cpp
Labels: enhancement

#2247 System test updates
  .github/workflows/system-tests.yaml
Labels: trigger-system-tests

#2251 Track mesh size in profiling record
  src/precice/impl/ParticipantImpl.cpp
Labels: enhancement

#2254 Turn substeps off for explicit coupling
  src/cplscheme/config/CouplingSchemeConfiguration.cpp
  src/cplscheme/config/CouplingSchemeConfiguration.hpp
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/ParallelExplicit.xml
  tests/serial/map-if-necessary/three-solvers/mixed-substeps/SerialExplicit.xml
  tests/serial/time/explicit/compositional/ReadWriteScalarDataWithSubcycling.xml
  tests/serial/time/explicit/parallel-coupling/ReadWriteScalarDataWithSubcycling.xml
  tests/serial/time/explicit/serial-coupling/ReadWriteScalarDataWithSubcycling.xml
Labels: usability, configuration

#2258 Fix HIP backend with Kokkos
  src/mapping/device/GinkgoRBFKernels.cpp
Labels: bug

#2259 Fix and cleanup ResidualSumPreConditioner update
  src/acceleration/impl/ResidualSumPreconditioner.cpp
Labels: bug
