Repository precice/precice, pull requests merged in 2025-04, with the labels that each got.

#2257 Enable running system tests in forks
  .github/workflows/system-tests.yaml
Labels: trigger-system-tests

#2260 Refactor preconditioners
  src/acceleration/impl/ConstantPreconditioner.cpp
  src/acceleration/impl/Preconditioner.hpp
  src/acceleration/impl/ResidualPreconditioner.cpp
  src/acceleration/impl/ResidualSumPreconditioner.cpp
  src/acceleration/impl/ValuePreconditioner.cpp
Labels: maintainability

#2269 Improve profiling merge robustness
  tools/profiling/precice-profiling
Labels: usability

#2275 Fix wording in error message
  src/precice/config/ParticipantConfiguration.cpp
Labels: bug

#2278 Fix test log filter to always display debug
  src/testing/GlobalFixtures.cpp
Labels: compatibility

#2279 Fix symbol visibility on Windows
  CMakeLists.txt
Labels: compatibility

#2280 Add required libraries on windows
  CMakeLists.txt
  docs/changelog/2280.md
Labels: compatibility
