Repository precice/precice, pull requests merged in 2025-02, with the labels that each got.

#2196 README.md: Update badges
  docs/README.md
Labels: documentation

#2205 Add emplaceSample to data to simplify tests
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/precice/tests/WatchIntegralTest.cpp
Labels: maintainability

#2052 Add system tests workflow
  .github/workflows/system-tests.yaml
Labels: trigger-system-tests

#2181 Add initial data in watch integrals and watch points
  docs/changelog/2181.md
  src/precice/impl/ParticipantState.cpp
  tests/serial/watch-integral/WatchIntegralScaleAndNoScale.cpp
Labels: enhancement

#2204 Use `setSampleAtTime` / `emplaceSampleAtTime` to simplify tests
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/com/tests/SerializedStamplesTest.cpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
Labels: maintainability

#2132 Skip non-existent data in exporter
  docs/changelog/2132.md
  src/io/ExportCSV.cpp
  src/io/ExportVTK.cpp
  src/io/ExportXML.cpp
Labels: bug

#2207 Make shape in gradients consistent
  src/com/tests/SerializedStamplesTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/CouplingData.cpp
  src/mesh/Data.cpp
  src/time/Sample.hpp
Labels: enhancement

#2206 Provide time window end to perform acceleration
  src/acceleration/Acceleration.hpp
  src/acceleration/AitkenAcceleration.cpp
  src/acceleration/AitkenAcceleration.hpp
  src/acceleration/BaseQNAcceleration.cpp
  src/acceleration/BaseQNAcceleration.hpp
  src/acceleration/ConstantRelaxationAcceleration.cpp
  src/acceleration/ConstantRelaxationAcceleration.hpp
  src/acceleration/test/AccelerationIntraCommTest.cpp
  src/acceleration/test/AccelerationSerialTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
Labels: maintainability

#2209 Simplify communication of time stamps
  src/com/SerializedStamples.cpp
  src/com/SerializedStamples.hpp
  src/com/tests/SerializedStamplesTest.cpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
Labels: maintainability

#2202 Add an error if participants use different preCICE versions
  docs/changelog/2202.md
  src/m2n/M2N.cpp
Labels: usability

#2213 Fix `getWindowEndTime()`
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/BaseCouplingScheme.hpp
  src/cplscheme/MultiCouplingScheme.cpp
  src/cplscheme/ParallelCouplingScheme.cpp
  src/cplscheme/SerialCouplingScheme.cpp
Labels: bug

#2203 Remove unnecessary write access to `CouplingData::sample()` and make `const`
  src/acceleration/Acceleration.cpp
  src/acceleration/BaseQNAcceleration.cpp
  src/com/SerializedStamples.cpp
  src/com/SerializedStamples.hpp
  src/cplscheme/BaseCouplingScheme.cpp
  src/cplscheme/CouplingData.cpp
  src/cplscheme/CouplingData.hpp
  src/mesh/Data.cpp
  src/mesh/Data.hpp
  src/time/Storage.cpp
  src/time/Storage.hpp
Labels: maintainability

#2193 Do not check exchangeSubsteps in QN acceleration
  src/acceleration/BaseQNAcceleration.cpp
Labels: maintainability

#2216 Refactor hashing into separate file
  src/com/ConnectionInfoPublisher.cpp
  src/sources.cmake
  src/tests.cmake
  src/utils/Hash.cpp
  src/utils/Hash.hpp
  src/utils/tests/HashTest.cpp
Labels: maintainability
